/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.hibernate.vo.SysDept;
import com.icss.hit.struts.form.AddDeptForm;

/** 
 * 添加部门
 * Creation date: 08-08-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action path="/addDept" name="addDeptForm" input="/dept/addDept.jsp" scope="request" validate="true"
 */
public class AddDeptAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddDeptForm addDeptForm = (AddDeptForm) form;// TODO Auto-generated method stub
		Department dt = new DepartmentBean();
		//实例化一个部门
		SysDept sd = new SysDept();
		sd.setSdInfo(addDeptForm.getSd_info());
		sd.setSdName(addDeptForm.getSd_name());
		sd.setSdTel(addDeptForm.getSd_tel());
		//添加部门
		if(dt.addDept(sd))
		{
			return mapping.findForward("AddDept.succeed");
		}
		else
		{
			return mapping.findForward("AddDept.faild");
		}
		
	}
}