/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMessage;

import com.icss.hit.bean.MeetingRoomBean;
import com.icss.hit.hibernate.vo.Room;
import com.icss.hit.struts.form.AddMeetingRoomForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-08-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="addMeetingRoom.success" path="/contents.jsp"
 * @struts.action-forward name="addMeetingRoom.error" path="/meeting/addMeetingRoom.jsp"
 */
public class AddMeetingRoomAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @author 许达
	 * 添加会议室信息
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		AddMeetingRoomForm rmForm = (AddMeetingRoomForm) form;// TODO Auto-generated method stub

		
		MeetingRoomBean getter = null;
		Room newMeetingRoom = null;
		getter = new MeetingRoomBean();
		
		
		
		newMeetingRoom = new Room();//实例化新的会议室
		newMeetingRoom.setRName(rmForm.getRoom_name());//初始化会议室名称
		newMeetingRoom.setRContain(Long.parseLong(rmForm.getRoom_capacity()));//初始化会议室容纳数量
		newMeetingRoom.setRInfo(rmForm.getRoom_describe());//初始化会议室备注信息
		
		

		

			if(getter.addRoom(newMeetingRoom) == 0){
				//成功添加
				return mapping.findForward("addMeetingRoom.success");
			}
			else if(getter.addRoom(newMeetingRoom) == 1){
				//发现有重名
				ActionErrors errors = new ActionErrors();
				errors.add("roomNameExist", new ActionMessage("AddMeetingRoom.roomNameExist"));
				saveErrors(request, errors);//返回重名的错误信息
				return mapping.findForward("addMeetingRoom.error");
			}
			else {
				//未知异常
				return mapping.findForward("addMeetingRoom.error");
			}
	}
}