/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.SysRoleBean;
import com.icss.hit.bean.interfaces.SysRoleDao;
import com.icss.hit.hibernate.vo.SysPower;
import com.icss.hit.hibernate.vo.SysRole;
import com.icss.hit.hibernate.vo.SysRolePower;
import com.icss.hit.struts.form.AddSysRoleForm;

/** 
 * 添加系统角色
 * Creation date: 08-10-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action path="/addSysRole" name="addSysRoleForm" input="/role/addSysRole.jsp" scope="request" validate="true"
 */
public class AddSysRoleAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddSysRoleForm addSysRoleForm = (AddSysRoleForm) form;// TODO Auto-generated method stub
		String[] powerArray = request.getParameterValues("sp_name");
		String rolename = addSysRoleForm.getSr_name();
		// 添加角色到系统
		SysRoleDao srd =new SysRoleBean();
		SysRole role = new SysRole();
		role.setSrName(rolename);
		long srId = srd.addSysRole(role);
		role.setSrId(srId);
		
		// 插入角色和权限
		for( String power : powerArray ){
			long id = Long.parseLong(power);
			SysPower sp = new SysPower();
			sp.setSpId(id);
			SysRolePower rolepower = new SysRolePower();
			
			rolepower.setSysPower(sp);
			rolepower.setSysRole(role);
			srd.addSysRolePower(rolepower);
		}
		return mapping.findForward("AddSysRole.succeed");
	}
}