/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.ManageRoomBean;
import com.icss.hit.bean.interfaces.manageRoomDao;
import com.icss.hit.hibernate.vo.Room;
import com.icss.hit.struts.form.AlterRoomForm;

/** 
 * 用于将修改的房间信息保存进数据库
 * Creation date: 08-10-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action path="/alterRoom" name="alterRoomForm" input="/manageAllRooms.do" scope="request" validate="true"
 * @struts.action-forward name="alterRoom.successd" path="/manageRoom.do"
 * @struts.action-forward name="alterRoom.fail" path="/manageRoom.do"
 */
public class AlterRoomAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//从前面获得表单
		AlterRoomForm alterRoomForm = (AlterRoomForm) form;// TODO Auto-generated method stub
		//房间ID
		String rid = alterRoomForm.getRid();
		//房间名字
		String rname = alterRoomForm.getRname();
		//房间容纳人数
		String rcontain = alterRoomForm.getRcontain();
		//房间信息
		String rInfo = alterRoomForm.getRinfo();
		//将是房间ID和容纳人数转化成为数字
		long roomID = Long.parseLong(rid);
		long contain = Long.parseLong(rcontain);
		
		manageRoomDao manageRoom = new ManageRoomBean();
		
		Room room = new Room();
		//room = manageRoom.readRoom(roomID);
		room.setRId(roomID);
		room.setRName(rname);
		room.setRContain(contain);
		room.setRInfo(rInfo);
		//将房间信息保存进数据库
		boolean result = manageRoom.saveRoom(room);
		//成功以后
		if(result==true)return mapping.findForward("alterRoom.successd");
		//如果失败了
		else return mapping.findForward("alterRoom.fail");
		
	}
}