/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.bean.ConfigWorkBean;
import com.icss.hit.bean.RoomBean;
import com.icss.hit.bean.interfaces.RoomDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.RoomReg;

/** 
 * 取消会议室申请
 * Creation date: 08-08-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="cancilReg.succeed" path="/meeting/registerMeetingRoomLog.jsp"
 * @struts.action-forward name="cancilReg.failed" path="/meeting/registerMeetingRoomLog.jsp"
 */
public class CancilRegAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 会议室申请ID
		long rrId=-1;
		// 当前登录用户ID
		long userId = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 页码
		int pageNo = 1;
		try{
			rrId = Long.parseLong(request.getParameter("rrId"));
		}
		catch(Exception e){
			rrId=-1;
		}
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			pageNo = 1;
		}
		RoomDao room  =new RoomBean();
     	// 取消当前用户会议申请
		room.delete(rrId, userId);
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("cancilReg.succeed"));
		redirect.addParameter("page", pageNo);
		return redirect;
	}
}