/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.icss.hit.bean.CardTypeBean;
import com.icss.hit.hibernate.vo.CardType;
import com.icss.hit.hibernate.vo.SysUser;
import com.icss.hit.struts.form.CardTypeAddForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-01-2009
 * 
 * XDoclet definition:
 * @struts.action path="/cardTypeAdd" name="cardTypeAddForm" input="/form/cardType.jsp" scope="request" validate="true"
 * @struts.action-forward name="cardTypeAdd.success" path="/card/cardType.jsp"
 */
public class CardTypeAddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @author 许达
	 * 实现名片夹的添加
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CardTypeAddForm cardTypeAddForm = (CardTypeAddForm) form;// TODO Auto-generated method stub

		long userId = 1L;//存储用户的Id
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		CardTypeBean getter = null;
		
		getter = new CardTypeBean();//实例化Bean
		
		
		CardType newCardType = new CardType();//实例化名片夹实例
		SysUser currentUser = new SysUser();
		currentUser.setSuId(userId);//根据用户ID初始化用户实例
		newCardType.setSysUser(currentUser);
		newCardType.setCtName(cardTypeAddForm.getNewCardType());//初始化要添加的名片夹信息
		
		
		
		
		
		System.out.print(cardTypeAddForm.getNewCardType().length());
		
			if(getter.updateCardType(newCardType) == 0){
				//成功添加信息的转向
				return mapping.findForward("CardTypeAdd.success");
			}
			else if(getter.updateCardType(newCardType) == 1){
				//出现重名错误
				ActionErrors errors = new ActionErrors();
				errors.add("newCardTypeTooLong",new ActionMessage("NewCardType.cardTypeNameRepeat"));
				saveErrors(request,errors);
				return mapping.findForward("CardTypeAdd.error");
			}
			else {
				//出现未知的异常
				return mapping.findForward("CardTypeAdd.error");
			}
		
	
		
	}
}