/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CardTypeBean;
import com.icss.hit.bean.interfaces.CardTypeDao;

/** 
 * 用于删除文件夹
 * Creation date: 08-11-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="CardTypeDel.fail" path="/CardType.do"
 * @struts.action-forward name="CardTypeDel.successd" path="/CardType.do"
 */
public class CardTypeDelAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//读取当前的用户的UserID
		long userId =1L;//存储用户的Id
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		//用于读取要删除的文件夹的ID，如果没有就转向失败
		String cardTypeID = request.getParameter("ID");
		if(cardTypeID==null)return mapping.findForward("CardTypeDel.fail");
		//文件夹的ID的传递
		long ID = Long.parseLong(cardTypeID);
		CardTypeDao cardType = new CardTypeBean();
		//判断是不是该用户的文件夹
		boolean result = cardType.isUsersType(userId, ID);
		if(result == false)return mapping.findForward("CardTypeDel.fail");
		//成功以后的操作
		result = cardType.deleteCardType(ID);
		if(result == false)return mapping.findForward("CardTypeDel.fail");
		//成功以后的操作
		return mapping.findForward("CardTypeDel.successd");
	}
}