/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.icss.hit.bean.*;
import com.icss.hit.hibernate.vo.*;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="cardType.success" path="/card/cardType.jsp"
 */
public class CardTypeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @author 许达 
	 * 实现名片夹显示
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		long userId =1L;//存储用户的Id
		
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		CardTypeBean getter = null;
		
		
		getter = new CardTypeBean();//实例化Bean
		
		//从数据库中得userId的所有名片夹信息 
		List<CardType> cardTypes = getter.getAllCardType(userId);
		
		//该用户有多少名片夹
		int cardTypeCount = getter.getCardTypeCount(userId);
		
		try{
			//cardTypes.setPath(request.getRealPath("/headphoto/")+"\\");
			request.setAttribute("cardTypesInfo",cardTypes);//返回名片夹信息
			request.setAttribute("cardTypesCount",cardTypeCount);//返回所有名片夹数量
			return mapping.findForward("cardType.success");//正确的映射
		}
		catch (Exception e){
			return mapping.findForward("cardType.error");//出错的映射
		}
		
		
		
		
	}
}