/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.SysPositionBean;
import com.icss.hit.bean.UserInfoBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.bean.interfaces.SysPositionDao;
import com.icss.hit.bean.interfaces.UserInfo;
import com.icss.hit.hibernate.vo.SysDept;
import com.icss.hit.hibernate.vo.SysPosition;
import com.icss.hit.hibernate.vo.SysUser;
import com.icss.hit.struts.form.ChangeInfoForm;

/** 
 * 管理员修改员工信息
 * Creation date: 08-12-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action path="/changeInfo" name="changeInfoForm" input="/form/changeInfo.jsp" scope="request" validate="true"
 */
public class ChangeInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ChangeInfoForm changeInfoForm = (ChangeInfoForm) form;// TODO Auto-generated method stub
		// 当前登录用户ID
		long userId = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 记住部门信息以及页码
		String deptNo= request.getParameter("dept");
		String pageNo = request.getParameter("page");
		// 得到员工ID
		String suId = request.getParameter("su_id");
		long workerId = -1;
		try{
			if( suId != null ){
				workerId = Long.parseLong(suId);
			}
		}
		catch(Exception e){
			workerId =-1;
		}
		if(workerId!=-1){
			// 得到修改信息
			String suUid = changeInfoForm.getSuUid();
			String suUsername = changeInfoForm.getSuUsername();
			String suSex = changeInfoForm.getSuSex();
			String suDept = changeInfoForm.getSuDept();
			String suPos = changeInfoForm.getSuPos();
			
			// 根据ID得到部门信息
			Department dept = new DepartmentBean();
			SysDept dp = dept.getDept(Long.parseLong(suDept));
			// 根据ID得到职位信息
			SysPositionDao pos = new SysPositionBean();
			SysPosition sp =pos.getPosition(Long.parseLong(suPos));
			
			UserInfo info = new UserInfoBean();
			SysUser user = info.getUserInfo(workerId);
			user.setSuUid(suUid);
			user.setSuUsername(suUsername);
			user.setSuSex(suSex);
			user.setSysDept(dp);
			user.setSysPosition(sp);
			// 更新用户信息
			info.updateUserInfo(user);
		}
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("changeInfo.succeed"));
		redirect.addParameter("dept",deptNo);
		redirect.addParameter("page", pageNo);
		return redirect;
	}
}