/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.bean.SysRoleBean;
import com.icss.hit.bean.UserInfoBean;
import com.icss.hit.bean.interfaces.SysRoleDao;
import com.icss.hit.bean.interfaces.UserInfo;
import com.icss.hit.hibernate.vo.SysRole;
import com.icss.hit.hibernate.vo.SysUser;

/** 
 * 修改用户系统角色
 * Creation date: 08-11-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="changeRole.failed" path="/role/roleArrange.jsp"
 * @struts.action-forward name="changeRole.succeed" path="/role/roleArrange.jsp"
 */
public class ChangeRoleAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 角色表ID
		long srId = -1;
		// 需要更改系统角色的用户ID
		long suId = -1;
		// 当前登陆用户ID
		long userId = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		try{
			if(request.getParameter("role")!=null){
				srId = Long.parseLong(request.getParameter("role"));
			}
			if(request.getParameter("suId")!=null){
				suId = Long.parseLong(request.getParameter("suId"));
			}
		}
		catch(Exception e){
			e.printStackTrace();
			return mapping.findForward("changeRole.failed");
		}
		String dept= request.getParameter("dept");
		String page = request.getParameter("page");
		SysRoleDao roleDao = new SysRoleBean();
		UserInfo info = new UserInfoBean();
		// 得到需要修改角色的用户信息
		SysUser user = info.getUserInfo(suId);
		SysRole role = roleDao.getRoleInfo(srId);
		if(user!=null){
			user.setSysRole(role);
			info.updateUserInfo(user);
		}
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("changeRole.succeed"));
		redirect.addParameter("dept",dept);
		redirect.addParameter("page", page);
		return redirect;
	}
}