/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.WorkListBean;
import com.icss.hit.bean.WorkPlanBean;
import com.icss.hit.bean.interfaces.WorkList;
import com.icss.hit.bean.interfaces.WorkPlanDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.Schedule;

/** 
 * 完成待办工作
 * Creation date: 08-05-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="completePlan.planListMore.succeed" path="/work/planListMore.jsp"
 * @struts.action-forward name="completePlan.planList.succeed" path="/work/planList.jsp"
 */
public class CompletePlanAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前登陆用户ID
		long userId=-1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// schedule表ID
		long schId=-1;
		// 页码
		int pageNo =1;
		// 所有人员的数量
		int count = 0;
		// 分页的数量
		int pageCount = 0;
		// 页面标记
		String flag=null;
		try{
			schId=Long.parseLong(request.getParameter("schId"));
		}
		catch(Exception e){
			schId=-1;
		}
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
			flag = request.getParameter("flag");
		}
		catch(Exception e){
			pageNo = 1;
			flag="planList";
		}
		if(schId!=-1){
			Schedule sch = new Schedule();
			WorkPlanDao wkDao = new WorkPlanBean();
			WorkList wList = new WorkListBean();
			// 得到指定日程
			sch=wkDao.getWorkPlanByTo(schId, userId);
			// 设置日程状态为完成
			sch.setSchComplete("1");
			boolean updateSuccess = wkDao.update(sch);
			// 存放查询结果
			List<Schedule> list =null;
			// 如果更新成功且跳转页面为planList.jsp
			if( updateSuccess && flag.equals("planList")){
				list = wList.getFiveWorkPlan(userId);
				request.setAttribute("planList", list);
				return mapping.findForward("completePlan.planList.succeed");
			}
			else if(updateSuccess && flag.equals("planListMore")){
				// 得到总数和分页
				count = wList.getAllWorkPlanCount(userId);
				pageCount = wList.getPageCount(count, WorkListBean.PAGE_SIZE);
				
				// 设置页面的范围
				pageNo = pageNo < 1? 1:pageNo;
				pageNo = pageNo > pageCount? pageCount: pageNo;
				
				list = wList.getAllWorkPlan(userId, pageNo);
				request.setAttribute("allWorkPlanList", list);
							
				// 生成前面的页面显示
				PageBean pagebean = new PageBean();
				pagebean.setLink("planListMore.do");
				pagebean.setTotal(pageCount);
				pagebean.setThispage(pageNo);
				
				request.setAttribute("pageString", pagebean.getPageString());
				return mapping.findForward("completePlan.planListMore.succeed");
			}
		}
		return mapping.findForward("completePlan.planList.succeed");
	}
}