/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.SysPositionBean;
import com.icss.hit.bean.SysRoleBean;
import com.icss.hit.bean.UserInfoBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.bean.interfaces.SysPositionDao;
import com.icss.hit.bean.interfaces.SysRoleDao;
import com.icss.hit.bean.interfaces.UserInfo;
import com.icss.hit.component.MD5;
import com.icss.hit.hibernate.vo.SysDept;
import com.icss.hit.hibernate.vo.SysPosition;
import com.icss.hit.hibernate.vo.SysRole;
import com.icss.hit.hibernate.vo.SysUser;
import com.icss.hit.struts.form.ConfirmAddWorkerForm;

/** 
 * 新增一个用户
 * Creation date: 08-12-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action path="/confirmAddWorker" name="confirmAddWorkerForm" input="/roleArrange.do" scope="request" validate="true"
 * @struts.action-forward name="confirmAddWorker.succeed" path="/roleArrange.do"
 */
public class ConfirmAddWorkerAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	/* (non-Javadoc)
	 * @see org.apache.struts.action.Action#execute(org.apache.struts.action.ActionMapping, org.apache.struts.action.ActionForm, javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ConfirmAddWorkerForm confirmAddWorkerForm = (ConfirmAddWorkerForm) form;// TODO Auto-generated method stub
		// 取得用户信息
		long userId = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		UserInfo userDao = new UserInfoBean();
		// 得到所有填入信息
		String suUid = confirmAddWorkerForm.getSuUid();
		String suUsername = confirmAddWorkerForm.getSuUsername();
		String suSex = confirmAddWorkerForm.getSuSex();
		String suPassword = confirmAddWorkerForm.getSuPassword();
		String suDept = confirmAddWorkerForm.getSuDept();
		String suPos = confirmAddWorkerForm.getSuPos();
		String suRole = confirmAddWorkerForm.getSuRole();
		String suTel = confirmAddWorkerForm.getSuTel();
		String suCellphone = confirmAddWorkerForm.getSuCellphone();
		String suHobby = confirmAddWorkerForm.getSuHobby();
		String suInfo = confirmAddWorkerForm.getSuInfo();
		String suEmail = confirmAddWorkerForm.getSuEmail();
		if(suUid!=null && suUsername !=null && suSex!=null && suPassword !=null && suDept !=null && suRole !=null){
			SysUser user = new SysUser();
			// 根据ID得到部门信息
			Department deptBean = new DepartmentBean();
			SysDept dp=null;
			dp = deptBean.getDept(Long.parseLong(suDept));
			
			// 根据ID得到职位信息
			SysPositionDao posBean = new SysPositionBean();
			SysPosition sp = null;
			sp=posBean.getPosition(Long.parseLong(suPos));
			// 根据ID得到角色信息
			SysRoleDao roleDao = new SysRoleBean();
			SysRole role = roleDao.getRoleInfo(Long.parseLong(suRole));
			user.setSuUid(suUid);
			user.setSuUsername(suUsername);
			user.setSuSex(suSex);
			user.setSuPassword(new MD5().getMD5Base32(suPassword));
			user.setSysDept(dp);
			user.setSysRole(role);
			user.setSysPosition(sp);
			if(suTel!=null){
				user.setSuTel(suTel);
			}
			if(suCellphone!=null){
				user.setSuCellphone(suCellphone);
			}
			if(suHobby!=null){
				user.setSuHobby(suHobby);
			}
			if(suInfo!=null){
				user.setSuInfos(suInfo);
			}
			if(suEmail!=null){
				user.setSuTel(suEmail);
			}
			// 新增一个用户
			userDao.updateUserInfo(user);
		}
		
		return mapping.findForward("confirmAddWorker.succeed");
	}
}