/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.bean.FileBean;
import com.icss.hit.hibernate.vo.Files;

/** 
 * MyEclipse Struts
 * Creation date: 08-08-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="DeleteFile.succeed" path="/FolderDetail.do" redirect="true"
 * @struts.action-forward name="DeleteFile.error" path="/MyFile.do" redirect="true"
 */
public class DeleteFileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 用户ID
		long uid = 1L;
		if( request.getSession().getAttribute("UserId") != null ){
			uid = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		long fId;
		try{
			fId = Long.parseLong(request.getParameter("id"));
		}catch( Exception e){
			return mapping.findForward("DeleteFile.error");
		}
		
		FileBean fileBean = new FileBean();
		Files files = fileBean.getFile(fId);
		if( files == null || files.getFileFolder().getSysUser().getSuId() != uid ){
			// 如果传递的参数不合法
			return mapping.findForward("DeleteFile.error");
		}
		
		fileBean.delete(files);
		String filePath = request.getRealPath("/file/" + uid + "/" + files.getFileFolder().getFfName() + "/")
			+ "\\" + files.getFName();
		System.out.println("filePath"+ filePath);
		fileBean.delete(filePath);
		
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("DeleteFile.succeed"));
		redirect.addParameter("id", files.getFileFolder().getFfId());
		return redirect;
	}
}