/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.WorkPlanBean;
import com.icss.hit.bean.interfaces.WorkPlanDao;

/** 
 * 删除一条日程安排，日程是由用户添加的。非用户添加的无权删除
 * Creation date: 08-04-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="DeleteWorkPlan.succeed" path="/WorkPlan.do" redirect="true"
 */
public class DeleteWorkPlanAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		long id = 5;
		long uid = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			uid = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 从地址栏中获得参数
		if( request.getParameter("id") != null ){
			id = Long.parseLong(request.getParameter("id").toString());
		}else{
			return mapping.findForward("DeleteWorkPlan.succeed");
		}
		
		WorkPlanDao bean = new WorkPlanBean();
		// 删掉一个日程
		bean.delete(id, uid);
		return mapping.findForward("DeleteWorkPlan.succeed");
	}
}