/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.MessageSaveBean;
import com.icss.hit.bean.interfaces.MessageDao;

/** 
 * 用于删除发送信息
 * Creation date: 08-09-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="deleteSendMes.fail" path="/outbox.do"
 * @struts.action-forward name="deleteSendMes.successd" path="/outbox.do"
 */
public class DeleteSendMesAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//读取信息的ID
		String mesID = request.getParameter("mesID");
		long mesId;
		if(mesID == null)return mapping.findForward("deleteSendMes.fail");
		try{
			mesId = Long.parseLong(mesID);
		}
		catch(Exception ex)
		{
			ex.getStackTrace();
			return mapping.findForward("deleteSendMes.fail");
		}
		MessageDao mes = new MessageSaveBean();
		//删除信息
		int del = mes.delSendMes(mesId);
		if(del == -1||del == 0)
		{
			return mapping.findForward("deleteSendMes.fail");
		}
		else
		{
			return mapping.findForward("deleteSendMes.successd");
		}
	}
}