/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CheckPower;
import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.SysPowerTypeBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.bean.interfaces.SysPowerTypeDao;

/** 
 * 删除用户权限
 * Creation date: 08-09-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="DeleteSysPower.succeed" path="/sysPowerList.do"
 */
public class DeleteSysPowerAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前用户ID
		long userId = -1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 判断用户权限
		CheckPower check = new CheckPower(userId);
		check.getPower();
		if( !check.check(CheckPower.ADMIN_POWER)){
			return mapping.findForward("NullLogin");
		}
		
		long spid=1;
		SysPowerTypeDao spt = new SysPowerTypeBean();
		String spId = request.getParameter("DeleteSpId");
			if( spId != null && spId.length()>0 )
				 spid = Long.parseLong(spId);
			else
			{
				return mapping.findForward("DeleteDept.faild");
			}
			//检查是否有角色使用该权限
			if(spt.checkSysPower(spid))
			{
				//删除该权限
			 spt.deleteSysPower(spid);
			}
			return mapping.findForward("DeleteSysPower.succeed");
	}
	}
