/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CheckPower;
import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.struts.form.ModifyCardForm;

/** 
 * 删除部门
 * Creation date: 08-08-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class DeleteDeptAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前用户ID
		long userId = -1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 判断用户权限
		CheckPower check = new CheckPower(userId);
		check.getPower();
		if( !check.check(CheckPower.ADMIN_DEPT)){
			return mapping.findForward("NullLogin");
		}
		
		long sdid=1;
		Department dt = new DepartmentBean();
		//通过url取得部门的ID
		String sdId = request.getParameter("DeleteSdId");
		if( sdId != null && sdId.length()>0 )
			sdid = Long.parseLong(sdId);
		else
		{
			return mapping.findForward("DeleteDept.faild");
		}
		//判断所选择删除的部门里面是否有员工
		boolean flag = dt.checkDept(sdid);
		//删除部门
		if(flag)
		{
			dt.deleteDept(sdid);
			return mapping.findForward("DeleteDept.succeed");
		}
		return mapping.findForward("DeleteDept.faild");
	}
}