/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.bean.InBoxBean;
import com.icss.hit.bean.WorkListBean;
import com.icss.hit.bean.WorkPlanBean;
import com.icss.hit.bean.interfaces.InBox;
import com.icss.hit.bean.interfaces.WorkList;
import com.icss.hit.bean.interfaces.WorkPlanDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.ReceiverInfo;
import com.icss.hit.hibernate.vo.Schedule;

/** 
 * 删除收件箱信息
 * Creation date: 08-07-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="deleteInBoxMessage.failed" path="/message/inBox.jsp"
 * @struts.action-forward name="deleteInBoxMessage.succeed" path="/message/inBox.jsp"
 */
public class DeleteInBoxMessageAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前登陆用户ID
		long userId=-1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// ReceiverInfo表ID
		long riId=-1;
		// 搜索方式
		String searchType=null;
		// 搜索内容
		String content = null;
		// 页码
		int pageNo =1;
		searchType = request.getParameter("searchType");
		content = request.getParameter("content");
		try{
			riId=Long.parseLong(request.getParameter("riId"));
		}
		catch(Exception e){
			riId=-1;
		}
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			pageNo = 1;
		}
		try{
			content = URLDecoder.decode(content, "UTF-8");
		}
		catch(Exception e){
			content = null;
		}
		if(riId!=-1){
			ReceiverInfo ri = new ReceiverInfo();
			InBox inbox = new InBoxBean();
			ri=inbox.getReceiverInfo(riId, userId);
			if(ri!=null){
				//不设置了，直接从收件箱删除
				inbox.delete(ri);
			}
		}
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("deleteInBoxMessage.succeed"));
		redirect.addParameter("searchType",searchType);
		redirect.addParameter("content", request.getParameter("content"));
		redirect.addParameter("page", pageNo);
		return redirect;
	}
}   