/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CheckPower;
import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.MessageSaveBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.ReceiverInfo;
import com.icss.hit.hibernate.vo.SysDept;

/** 
 * 部门列表
 * Creation date: 08-08-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class DeptListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前用户ID
		long userId = -1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 判断用户权限
		CheckPower check = new CheckPower(userId);
		check.getPower();
		if( !check.check(CheckPower.ADMIN_DEPT)){
			return mapping.findForward("NullLogin");
		}
		
		
		Department dt = new DepartmentBean();
		int count = dt.getDeptCount();
		int pageCount =0;
		if( count != 0 ){
			// 得到总页数
			pageCount = dt.getPageCount(count, MessageSaveBean.PAGE_SIZE);
		}
		
		// 当前页数
		int pageNo = 1;
		if( request.getParameter("page") != null ){
			try{
				pageNo = Integer.parseInt(request.getParameter("page"));
			}catch( Exception e){
				pageNo = 1;
			}
		}
		// 得到当前页数的内容
		if( pageCount != 0){
			//得到所有的部门的列表
			List<SysDept> deptList = dt.getAllDeptByPage(pageNo);
			request.setAttribute("deptList", deptList);
			// 输出分页的信息
			PageBean bean = new PageBean();
			bean.setTotal(pageCount);
			bean.setLink("./deptList.do");
			bean.setThispage(pageNo);
			request.setAttribute("page", bean.getPageString());
		}

		return mapping.findForward("DeptList.succeed");
		
	}
}