/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.FileBean;
import com.icss.hit.bean.FileFolderBean;
import com.icss.hit.bean.interfaces.FileDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.Files;

/** 
 * 页面跳转，显示某一指定文件夹内的详细信息
 * Creation date: 08-07-2009
 * @author 万里鹏
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="FolderDetail.succeed" path="/filepage/folderDetail.jsp"
 */
public class FolderDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 用户ID
		long uid = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			uid = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 文件夹的ID
		long ffId = 1;
		// 从地址栏中得到参数
		if( request.getParameter("id") != null ){
			try{
				ffId = Long.parseLong(request.getParameter("id").toString());
			}catch( Exception e ){
				// 如果参数传递不正确，则返回
				return mapping.findForward("FolderDetail.error");
			}
		}else{
			return mapping.findForward("FolderDetail.error");
		}
		
		
		// 页数
		int page = 1;
		if( request.getParameter("page") != null ){
			try{
				ffId = Long.parseLong(request.getParameter("page").toString());
			}catch( Exception e ){
				// 如果参数传递不正确，则默认为1
				page = 1;
			}
		}
		
		FileDao filedao = new FileBean();
		// 得到所有条数
		int count = filedao.getFilesCount(ffId, uid);
		System.out.println(count);
		// 总的页数
		int pageCount = filedao.getPageCount(count, FileBean.PAGE_SIZE);
		List<Files> list = filedao.getFilesByPage(ffId, uid, page);
		
		request.setAttribute("list", list);
		String folderPath = "file/" + uid;
		request.setAttribute("folderPath", folderPath);
		request.setAttribute("share", new FileFolderBean().getFileFolder(ffId, uid).getFfShare());
		
		PageBean pageBean = new PageBean();
		pageBean.setTotal(pageCount);
		pageBean.setThispage(page);
		pageBean.setLink("FolderDetail.do");
		pageBean.addParam("id=" + ffId );
		request.setAttribute("pageString", pageBean.getPageString());
		
		return mapping.findForward("FolderDetail.succeed");
	}
}