/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CardBean;
import com.icss.hit.bean.OtherInfoBean;
import com.icss.hit.bean.interfaces.CardDao;
import com.icss.hit.bean.interfaces.OtherInfo;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.Card;
import com.icss.hit.hibernate.vo.SysUser;

/** 
 * 得到共享名片夹
 * Creation date: 08-03-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="getShareCardById.succeed" path="/card/shareCardList.jsp"
 */
public class GetShareCardByIdAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		int userId = -1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Integer.parseInt(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		int pageNo = 1;
		try{
			userId = Integer.parseInt(request.getParameter("userId"));
		}catch(Exception e){
			return mapping.getInputForward();
		}
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}catch(Exception e){
			// 如果数据异常
			pageNo = 1;
		}
		
		// 所有人员的数量
		int count = 0;
		// 分页的数量
		int pageCount = 0;
		// 得到搜索的数据
		List<Card> list = null;
		
		if( userId != -1){
			CardDao share = new CardBean();
			
			// 得到总数和分页
			count = share.getShareCardCount(userId);
			pageCount = share.getPageCount(count, OtherInfoBean.PAGE_SIZE);
			
			// 设置页面的范围
			pageNo = pageNo < 1? 1:pageNo;
			pageNo = pageNo > count? count: pageNo;
			
			list = share.getShareCard(userId, pageNo);
			request.setAttribute("shareCardList", list);
						
			// 生成前面的页面显示
			PageBean pagebean = new PageBean();
			pagebean.addParam("userId="+userId);
			pagebean.setLink("getShareCardById.do");
			pagebean.setTotal(pageCount);
			pagebean.setThispage(pageNo);
			
			request.setAttribute("pageString", pagebean.getPageString());
		}
		return mapping.findForward("getShareCardById.succeed");
	}
}