/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;


import com.icss.hit.bean.CheckPower;
import com.icss.hit.bean.OutputGraphBean;
import com.icss.hit.bean.interfaces.outputGraphDao;
import com.icss.hit.struts.form.GraphOutputForm;
import com.icss.hit.component.DrawLine;
import java.awt.Color;
/** 
 * 用于写图片
 * Creation date: 08-10-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action path="/graphOutput" name="graphOutputForm" input="/outputGraph.do" scope="request" validate="true"
 */
public class GraphOutputAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GraphOutputForm graphOutputForm = (GraphOutputForm) form;// TODO Auto-generated method stub
		//获得用户的ID
		long uid;
		if( request.getSession().getAttribute("UserId") != null ){
			uid = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}

		// 判断用户权限
		CheckPower check = new CheckPower(uid);
		check.getPower();
		if( !check.check(CheckPower.ADMIN_ROOM_REG)){
			return mapping.findForward("NullLogin");
		}
		
		
		String month = graphOutputForm.getMonth();
		String year = graphOutputForm.getYear();
		// 得到保存图片的硬盘路径
		String path = request.getRealPath("/file/pie/") + "\\"+year+"_"+month + "_fileline.jpg";
		outputGraphDao outputGraph = new OutputGraphBean();
		List<Integer> dayList = outputGraph.getRoomsRegistCount(year, month);
		DrawLine drawLine = DrawLine.getInstance();
		drawLine.setXYPointList("点集1");
		//添加点数
		for(int i = 1;i <=dayList.size();i++)
		{
			//获得每一天的存有的申请的数值
			double dayCount = (double)dayList.get(i-1);
			drawLine.addPoint((double)i, dayCount);
		}
		//添加进点集
		drawLine.addPointList();
		//初始化
		drawLine.init();
		//设置折线图标题
		drawLine.setTitle(year+"年"+month+"月"+"会议室申请图");
		//设置X轴名字（天数）
		drawLine.setXTitle("天数");
		//设置Y轴名字（每日申请数量）
		drawLine.setYTitle("每日申请数量");
		//图片的高度
		drawLine.setWidth(746);
		drawLine.setHeight(280);
		drawLine.setBgColor(Color.LIGHT_GRAY);
		drawLine.setForeColor(Color.white);
		drawLine.setSpaceLineColor(Color.LIGHT_GRAY);
		
		//保存的文件名
		if(drawLine.saveAbs(path))
		{
			ActionRedirect redirect = new ActionRedirect(mapping.findForward("graphOutput.successd"));
			redirect.addParameter("pic", "pic");
			redirect.addParameter("month", month);
			redirect.addParameter("year", year);
			return redirect;
		}
		
		return null;
		
	}
}