/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.bean.MeetingRoomBean;
import com.icss.hit.bean.RoomBean;
import com.icss.hit.bean.interfaces.MeetingRoomDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.RoomReg;

/** 
 * MyEclipse Struts
 * Creation date: 08-10-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="handleUnsettledRoom.succeed" path="manageMeetingRoom.do"
 */
public class HandleUnsettledRoomAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		long rrId=-1;
		// 测试数据
		long userId = 1;
		// 操作方式 admit为允许 cancil为不同意
		String type=null;
		int pageNo = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			pageNo=1;
		}
		try{
			
			rrId = Long.parseLong(request.getParameter("rrId"));
		}
		catch(Exception e){
			rrId=-1;
		}
		try{
			type = request.getParameter("type");
		}
		catch(Exception e){
			type=null;
		}
		if(rrId!=-1 && type!=null)
		{
			MeetingRoomDao room  = new MeetingRoomBean();
			RoomReg rr = room.getRoomRegByID(rrId);
			if(type.equals("admit")){
				rr.setRrPass("1");
			}
			else if(type.equals("cancil")){
				rr.setRrPass("0");
			}
			room.update(rr);
			System.out.println("更新成功");
		}
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("handleUnsettledRoom.succeed"));
		redirect.addParameter("page", pageNo);
		return redirect;
	}
}