/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.MessageSaveBean;
import com.icss.hit.bean.UserInfoBean;
import com.icss.hit.bean.WorkListBean;
import com.icss.hit.bean.interfaces.MessageDao;
import com.icss.hit.bean.interfaces.UserInfo;
import com.icss.hit.bean.interfaces.WorkList;
import com.icss.hit.hibernate.vo.Schedule;
import com.icss.hit.hibernate.vo.SysUser;

/** 
 * MyEclipse Struts
 * Creation date: 08-03-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="Home.error" path="/login.jsp"
 * @struts.action-forward name="Home.succeed" path="/home/home.jsp"
 */
public class HomeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		long id = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			id = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		UserInfo info = new UserInfoBean();
		// 得到用户的详细资料
		SysUser user = info.getUserInfo(id);
		request.setAttribute("userInfo", user);
		
		// 得到用户的未读信息的数量
		MessageDao msgdao = new MessageSaveBean();
		request.setAttribute("messageCount",msgdao.getMessageNotRead(id));
		
		// 得到待办事项
		WorkList work = new WorkListBean();
		List<Schedule> list = work.getFiveWorkPlan(id);
		request.setAttribute("planList", list);
		return mapping.findForward("Home.succeed");
	}
}