/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.InBoxBean;
import com.icss.hit.bean.interfaces.InBox;
import com.icss.hit.hibernate.vo.ReceiverInfo;

/** 
 * 收件箱留言详细信息
 * Creation date: 08-06-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="inBoxDetails.succeed" path="/work/inBoxDetails.jsp"
 */
public class InBoxDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前登录用户ID
		long userId=-1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		// receiverInfo表ID
		long riId=-1;
		// 页码
		int pageNo=1;
		// 搜索方式
		String searchType=null;
		// 搜索内容
		String content=null;
		// 存放跳转参数
		String forwardString=null;
		try{
			riId=Long.parseLong(request.getParameter("riId"));
			searchType= request.getParameter("searchType");
			content = request.getParameter("content");
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			riId=-1;
			pageNo=1;
		}
		if(riId!=-1){
			ReceiverInfo ri = new ReceiverInfo();
			InBox inbox = new InBoxBean();
			
			ri=inbox.getReceiverInfo(riId, userId);
			request.setAttribute("inBoxDetails", ri);
			
			// 设置留言状态为已读状态
			ri.setRiRead("1");
			inbox.update(ri);
			
			forwardString="inBox.do?searchType="+searchType+"&content="+URLEncoder.encode(content)+"&page="+pageNo;
			request.setAttribute("forwardString", forwardString);
			return mapping.findForward("inBoxDetails.succeed");
		}
		return mapping.findForward("inBoxDetails.failed");
	}
}