/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.icss.hit.bean.UserInfoBean;
import com.icss.hit.bean.interfaces.UserInfo;
import com.icss.hit.struts.form.LoginForm;
/** 
 * 对登录的验证
 * Creation date: 07-28-2009
 * @author 万里鹏
 * XDoclet definition:
 * @struts.action path="/Login" name="loginForm" input="/login/login.jsp" scope="request" validate="true"
 * @struts.action-forward name="Login.error" path="/login/login.jsp"
 * @struts.action-forward name="Login.succeed" path="/index.jsp"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("deprecation")
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		
		String code = loginForm.getCode();
		
		// 得到session中存储的注册码
		String validatecode = request.getSession().getAttribute("validateCode").toString().toLowerCase();
		// 验证验证码填写的合法性
		if( !code.toLowerCase().equals(validatecode)){
			ActionErrors errors = new ActionErrors();
			errors.add("code", new ActionMessage("Login.ErrorCode"));
			saveErrors(request, errors);
			return mapping.findForward("Login.error");
		}
		String username = loginForm.getUsername();
		String password = loginForm.getPassword();
		
		// 验证用户名与密码是否匹配
		UserInfo info = new UserInfoBean();
		long result = info.validata(username, password);
		if( result > 0){
			// 用户ID保存到Session中
			request.getSession().setAttribute("UserId", result);
			return mapping.findForward("Login.succeed");
		}else{
			ActionErrors errors = new ActionErrors();
			errors.add("login", new ActionMessage("Login.Error"));
			saveErrors(request, errors);
			return mapping.findForward("Login.error");
		}
	}
}