/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CheckPower;
import com.icss.hit.bean.MeetingRoomBean;
import com.icss.hit.bean.interfaces.MeetingRoomDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.RoomReg;

/** 
 * 得到未审批的会议室预约
 * Creation date: 08-10-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="manageMeetingRoom.failed" path="/meeting/manageMeetingRoom.jsp"
 * @struts.action-forward name="manageMeetingRoom.succeed" path="/meeting/manageMeetingRoom.jsp"
 */
public class ManageMeetingRoomAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前登陆用户ID
		long userId = -1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 判断用户权限
		CheckPower check = new CheckPower(userId);
		check.getPower();
		if( !check.check(CheckPower.ADMIN_ROOM_REG)){
			return mapping.findForward("NullLogin");
		}
		
		// 查询页码
		int pageNo = 1;
		
		// 所有人员的数量
		int count = 0;
		// 分页的数量
		int pageCount = 0;
		// 得到搜索的数据
		List<RoomReg> list = null;
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			pageNo =1;
		}
		
		if( userId != -1){
			MeetingRoomDao meeting = new MeetingRoomBean();
			
			// 得到总数和分页
			count = meeting.getAllUnsettledRoomCount();
			pageCount = meeting.getPageCount(count, MeetingRoomBean.PAGE_SIZE);
			// 设置页面的范围
			pageNo = pageNo < 1? 1:pageNo;
			pageNo = pageNo > pageCount? pageCount: pageNo;
			
			// 得到未审批的会议室预约
			list = meeting.getAllUnsettledRoom();
			if(list.size()>0){
				request.setAttribute("unsettledRoomList", list);
				request.setAttribute("page",pageNo);			
				// 生成前面的页面显示
				PageBean pagebean = new PageBean();
				pagebean.setLink("manageMeetingRoom.do");
				pagebean.setTotal(pageCount);
				pagebean.setThispage(pageNo);
				request.setAttribute("pageString", pagebean.getPageString());
			}
		}
		return mapping.findForward("manageMeetingRoom.succeed");
	}
}