/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.bean.ManageRoomBean;
import com.icss.hit.bean.interfaces.manageRoomDao;
import com.icss.hit.hibernate.vo.Room;
import com.icss.hit.struts.form.ManageAllRoomsForm;

/** 
 * 用于判断点击的是修改还是删除，同时进行参数的传递
 * Creation date: 08-10-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action path="/manageAllRooms" name="manageAllRoomsForm" input="/manageRoom.do" scope="request" validate="true"
 * @struts.action-forward name="manageAllRooms.fail" path="fgdsa"
 * @struts.action-forward name="manageAllRooms.successd" path="fdsafas"
 */
public class ManageAllRoomsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//传递表单
		ManageAllRoomsForm manageAllRoomsForm = (ManageAllRoomsForm) form;// TODO Auto-generated method stub
		manageRoomDao manageRoom = new ManageRoomBean();
		String type = manageAllRoomsForm.getType();
		//房间ID
		long roomID = Long.parseLong(request.getParameter("roomID"));
		
		//删除
		if(type.equals("del"))
		{
			boolean result = manageRoom.deleteRoom(roomID);
			if(result==true)return mapping.findForward("manageAllRooms.successd");
			else return mapping.findForward("manageAllRooms.fail");
		}
		//修改
		else if(type.equals("alter"))
		{
			// 带参数的页面跳转
			ActionRedirect redirect = new ActionRedirect(mapping.findForward("manageAllRooms.redirect"));
			redirect.addParameter("roomID", roomID);
			return redirect;
			
		}
		
		
		
		return mapping.findForward("manageAllRooms.successd");
	}
}