/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.bean.MeetingRoomBean;
import com.icss.hit.bean.interfaces.MeetingRoomDao;
import com.icss.hit.hibernate.vo.RoomReg;

/** 
 * 会议室申请详细信息
 * Creation date: 08-10-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="meetingRegDetails.succeed" path="/meeting/meetingRegDetails.jsp"
 */
public class MeetingRegDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 会议室申请ID
		long rrId=-1;
		// 当前登录用户ID
		long userId = 1;
		// 页码
		int pageNo = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			pageNo=1;
		}
		try{
			rrId = Long.parseLong(request.getParameter("rrId"));
		}
		catch(Exception e){
			rrId=-1;
		}
		if(rrId!=-1)
		{
			MeetingRoomDao room  = new MeetingRoomBean();
			RoomReg rr = room.getRoomRegByID(rrId);
			request.setAttribute("meetingRegDetails",rr );
			request.setAttribute("forwardString","manageMeetingRoom.do?page="+pageNo);
		}
		
		return mapping.findForward("meetingRegDetails.succeed");
	}
}