/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.MeetingLaunchBean;
import com.icss.hit.bean.interfaces.meetingLaunchDao;
import com.icss.hit.hibernate.vo.Room;

/** 
 * 判断有没有权利发起会议，并且进行转向
 * Creation date: 08-09-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class MeetingLaunchAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//查看有没有申请会议，没有的话就直接不给发起会议的权利
		//读当前用户ID
		long uid=1;
		if( request.getSession().getAttribute("UserId") != null ){
			uid = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		meetingLaunchDao meetingLaunch = new MeetingLaunchBean();
		long existRegist = meetingLaunch.getAccess(uid);
		//没有通过申请
		if(existRegist==-1 || existRegist == 0 )
		{
			return mapping.findForward("meetingLaunch.fail");
		}
		//通过申请就转向成功
		List<Room> rooms=meetingLaunch.getRooms(uid);
		request.setAttribute("roomList",rooms);
		return mapping.findForward("meetingLaunch.successd");
	}
}