/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.File;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.MeetingAttendBean;
import com.icss.hit.bean.interfaces.MeetingAttendDao;
import com.icss.hit.component.MD5;
import com.icss.hit.hibernate.vo.Meeting;
import com.icss.hit.hibernate.vo.SysUser;

/** 
 * 会议详细信息
 * Creation date: 08-09-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="meetingDetails.failed" path="/meeting/meetingDetails.jsp"
 * @struts.action-forward name="meetingDetails.succeed" path="/meeting/meetingDetails.jsp"
 */
public class MeetingDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		// 当前登陆用户ID
		long userId=-1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 会议ID
		long initiatorId=-1;
		// 页码
		int pageNo=1;
		String forwardString=null;
		try{
			initiatorId=Long.parseLong(request.getParameter("initiator"));
		}
		catch(Exception e){
			initiatorId=-1;
		}
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			pageNo=1;
		}
		if(initiatorId!=-1){
			MeetingAttendDao meeting = new MeetingAttendBean();
			Meeting meetingDetails = meeting.getMeetingDetails(initiatorId);
			List<SysUser> attendee = meeting.getAllAssociateSysUser(initiatorId);
			// 会议详细信息
			request.setAttribute("meetingDetails", meetingDetails);
			// 参与会议人员
			request.setAttribute("attendeeList", attendee);
			// 设置当前用户ID
			request.setAttribute("userId", userId);
			forwardString="meetingAttend.do?page="+pageNo;
			request.setAttribute("forwardString", forwardString);
			
			// 检查是否存在会议记录
			String recordname = new MD5().getMD5Base16(initiatorId+"");
			File record = new File(request.getRealPath("/meetingRecord/") + "\\" + recordname + ".html");
			if( !record.exists() ){
				record = new File(request.getRealPath("/meetingRecord/") + "\\" + recordname + ".htm");
				if( record.exists()){
					request.setAttribute("record", recordname + ".htm");
				}
			}else{
				request.setAttribute("record", recordname + ".html");
			}
			return mapping.findForward("meetingDetails.succeed");
		}
		return mapping.findForward("meetingDetails.failed");
	}
}