/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CardBean;
import com.icss.hit.bean.interfaces.CardDao;
import com.icss.hit.hibernate.vo.Card;
import com.icss.hit.hibernate.vo.CardType;
import com.icss.hit.hibernate.vo.SysUser;
import com.icss.hit.struts.form.ModifyCardForm;

/** 
 * 修改名片
 * Creation date: 08-03-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action path="/modifyCard" name="modifyCardForm" input="/card/modifyCard.jsp" scope="request" validate="true"
 */
public class ModifyCardAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifyCardForm modifyCardForm = (ModifyCardForm) form;
		//实例化一个用户
		//通过session获取用户id，并判断是否为空
		long userId=1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		CardDao cd = new CardBean();
		// 实例化一个名片 
		Card card = cd.getCard(modifyCardForm.getCd_id());
		card.setCdName(modifyCardForm.getCd_name());
		card.setCdCellphone(modifyCardForm.getCd_cellphone());
		card.setCdCompany(modifyCardForm.getCd_company());
		card.setCdPosition(modifyCardForm.getCd_position());
		card.setCdEmail(modifyCardForm.getCd_email());
		card.setCdFax(modifyCardForm.getCd_fax());
		card.setCdInfos(modifyCardForm.getCd_info());
		card.setCdTel(modifyCardForm.getCd_tel());
		card.setCdShare(modifyCardForm.getCd_share());
		if( !modifyCardForm.getCd_sex().equals("0") )
			card.setCdSex(modifyCardForm.getCd_sex());
		//实例化一个名片夹分类
		CardType ct = new CardType();
		if(modifyCardForm.getCt_name()!=null&&modifyCardForm.getCt_name().length()>0)
		{
		
			ct.setCtId(Long.parseLong(modifyCardForm.getCt_name()));
		}

		
		//实例化一个用户，通过用户id获取信息
		SysUser user = new SysUser();
		user.setSuId(userId);
		ct.setSysUser(user);
		card.setCardType(ct);
		//更新名片
		if(cd.updateCard(card))
		{
			return mapping.findForward("ModifyCard.succeed");
		}
		else
		{
			return mapping.findForward("ModifyCard.faild");
		}
	}
}