/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.hibernate.vo.SysDept;
import com.icss.hit.struts.form.ModifyDeptForm;

/** 
 * 修改名片
 * Creation date: 08-08-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action path="/modifyDept" name="modifyDeptForm" input="/toModifyDept.do" scope="request" validate="true"
 */
public class ModifyDeptAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifyDeptForm modifyDeptForm = (ModifyDeptForm) form;// TODO Auto-generated method stub
		Department dt = new DepartmentBean();
		SysDept dept = dt.getDept(Long.parseLong(modifyDeptForm.getSd_id()));
		dept.setSdInfo(modifyDeptForm.getSd_info());
		dept.setSdName(modifyDeptForm.getSd_name());
		dept.setSdTel(modifyDeptForm.getSd_tel());
		//更新部门
		if(dt.updateDept(dept))
		{
			return mapping.findForward("ModifyDept.succeed");
		}
		else
		{
			return mapping.findForward("ModifyDept.faild");
		}
	}
}