/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.SchduletimeBean;
import com.icss.hit.bean.interfaces.ScheduletimeDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.Schedule;

/** 
 * 用于按月份查找内容
 * Creation date: 08-05-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="monthSearch.fail" path="/work/canlenderSearch.jsp"
 */
public class MonthSearchAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		long userId = 1L;
		// 得到用户ID
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		//得到date的信息
		String date = request.getParameter("date");
		//date的判断
		if(date == null||date.length()<7||date.length()>8)return mapping.findForward("monthSearch.fail");
		String year = null;
		String month = null;
		Date beginTime = new Date();
		Date endTime = new Date();
		int Year = 2009;
		int Month = 0;
		
		
		//格式如2009n7y
			if(date.length() == 7)
			{
				year = date.substring(0, 4);
				month = date.substring(5, 6);
				Year = Integer.parseInt(year);
				Month = Integer.parseInt(month);
				
			}
		//格式如2009n12y
			else if(date.length() == 8)
			{
				year = date.substring(0, 4);
				month = date.substring(5, 7);
				Year = Integer.parseInt(year);
				Month = Integer.parseInt(month);
				
			}
			//开始时间（月份）
			GregorianCalendar calendar = new GregorianCalendar(Year,Month-1,0,0,0,0);
			calendar.add(Calendar.DAY_OF_YEAR, 1);
			beginTime = calendar.getTime();
			//结束时间（月份）
			GregorianCalendar calendar1 = new GregorianCalendar(Year,Month,0,0,0,0);
			calendar1.add(Calendar.DAY_OF_YEAR, 1);
			endTime = calendar1.getTime();
			System.out.println(beginTime.toLocaleString());
			System.out.println(endTime.toLocaleString());
			
			
			ScheduletimeDao schduleWork = new SchduletimeBean();
			int count = schduleWork.getSchduleWorkCount(userId, beginTime, endTime);
			//System.out.println(count);
			int pageCount = 0;
			if( count != 0 ){
					// 得到总页数
					pageCount = schduleWork.getPageCount(count, SchduletimeBean.PAGE_SIZE);
				
				
				// 当前页数
				int pageNo = 1;
				if( request.getParameter("page") != null ){
					try{
						pageNo = Integer.parseInt(request.getParameter("page"));
					}catch( Exception e){
						pageNo = 1;
					}
				}
				
				// 得到当前页数的内容
				if( pageCount != 0){
					List<Schedule> list = schduleWork.getSchduleWorkByPage(userId, pageNo, beginTime, endTime);
					System.out.println(list.isEmpty());
					request.setAttribute("schList", list);
					
					// 输出分页的信息
					PageBean bean = new PageBean();
					bean.setTotal(pageCount);
					bean.setLink("/OA/monthSearch.do");
					bean.addParam("date="+date);
					bean.setThispage(pageNo);
					
					request.setAttribute("page", bean.getPageString());
				}
				request.setAttribute("MonthExistArrange", 1);
				List<Date> dateList = new ArrayList<Date>();
				dateList.add(beginTime);
				request.setAttribute("MonthOfSearch", dateList);
				return mapping.findForward("monthSearch.successd");
			}
			else{
				request.setAttribute("MonthExistArrange", 0);
				return mapping.findForward("monthSearch.fail");
			}
	}
}