/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CardBean;
import com.icss.hit.bean.CardTypeBean;
import com.icss.hit.bean.interfaces.CardDao;
import com.icss.hit.bean.interfaces.CardTypeDao;
import com.icss.hit.hibernate.vo.Card;
import com.icss.hit.hibernate.vo.CardType;
import com.icss.hit.struts.form.AddCardForm;

/** 
 * 添加名片
 * Creation date: 08-06-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class NewCardAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		long userId = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		CardTypeDao cd = new CardTypeBean();
		//得到属于userId的所有的名片夹分类
		List<CardType> list = cd.getAllCardType(userId);
		request.setAttribute("ctnameList", list);
		return mapping.findForward("NewCard.succeed");
		
	}
}