/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CheckPower;

/** 
 * MyEclipse Struts
 * Creation date: 08-08-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="newMeetingRoom.success" path="/meeting/addMeetingRoom.jsp"
 * @struts.action-forward name="newMeetingRoom.error" path="/login.jsp"
 */
public class NewMeetingRoomAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			// 当前用户ID
			long userId = -1;
			if( request.getSession().getAttribute("UserId") != null ){
				userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
			}else{
				return mapping.findForward("NullLogin");
			}
			// 判断用户权限
			CheckPower check = new CheckPower(userId);
			check.getPower();
			if( !check.check(CheckPower.ADMIN_ROOM)){
				return mapping.findForward("NullLogin");
			}
			
			return mapping.findForward("newMeetingRoom.success");
		}
		catch(Exception e){
			return mapping.findForward("newMeetingRoom.success");
			
		}
	}
}
