/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CheckPower;
import com.icss.hit.bean.SysRoleBean;
import com.icss.hit.bean.interfaces.SysRoleDao;
import com.icss.hit.hibernate.vo.SysPower;
import com.icss.hit.hibernate.vo.SysPowerType;

/** 
 * 新建系统角色
 * Creation date: 08-10-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class NewSysRoleAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前用户ID
		long userId = -1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 判断用户权限
		CheckPower check = new CheckPower(userId);
		check.getPower();
		if( !check.check(CheckPower.ADMIN_ROLE)){
			return mapping.findForward("NullLogin");
		}
		
		SysRoleDao srd = new SysRoleBean();
		//得到所有的系统权限列表
		List<SysPower> spList = srd.getAllSysPower();
		//得到所有的系统权限分类列表
		List<SysPowerType> sptList = srd.getAllsysPowerType();
		request.setAttribute("spList", spList);
		request.setAttribute("sptList", sptList);
		return mapping.findForward("NewSysRole.succeed");
	}
}