/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.MessageSaveBean;
import com.icss.hit.bean.interfaces.MessageDao;
import com.icss.hit.hibernate.vo.Message;
import com.icss.hit.hibernate.vo.ReceiverInfo;
import com.icss.hit.hibernate.vo.SysUser;
import com.icss.hit.struts.form.NewUserMessageForm;

/** 
 * 写用户的新建信息
 * Creation date: 08-06-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action path="/newUserMessage" name="newUserMessageForm" input="/form/newUserMessage.jsp" scope="request" validate="true"
 */
public class NewUserMessageAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NewUserMessageForm newUserMessageForm = (NewUserMessageForm) form;// TODO Auto-generated method stub
		//读取用户的ID
		long uid = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			uid = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		long mesID = -2;
		long ReciverID = -2;
		Long result;
		String riBox = "0";
		SysUser user = new SysUser();
		user.setSuId(uid);
		Date date = new Date();
		// 类型
		String optype = newUserMessageForm.getType();
		// 用户ID集合
		String userIds = newUserMessageForm.getIdArray();
		// 标题
		String mesTitle = newUserMessageForm.getMessageTitle();
		// 内容
		
		
		String mesContent = newUserMessageForm.getMessagecontent();
		String[] Users;           
		Users = userIds.split(",");                        //分出来的用户ID
		//设置信息的基本信息
		Message myMessage = new Message();
		myMessage.setMsTitle(mesTitle);
		myMessage.setMsContent(mesContent);
		myMessage.setMsSendtime(date);
		myMessage.setSysUser(user);
		myMessage.setMsDelete("0");
		MessageDao messageSave = new MessageSaveBean();
		//标示新建所属信箱，1为发件箱，2为草稿箱,3为收件箱
		if(optype.equals("send"))
		{
			//储存在发件箱中，当用户想发送邮件是，放入发件箱，注意的是邮件的发送人的邮箱写的是发件箱，所有接收人的邮箱写的是收件箱
			riBox = "3";
			myMessage.setMsBox("1");
			
		}
		else if(optype.equals("save"))
		{	
			//储存在草稿箱，当用户想保存草稿的时候，放入草稿箱，注意的是邮件的发送人的邮箱写的是草稿箱，所有接收人的邮箱写的是草稿箱
			riBox = "2";
			myMessage.setMsBox("2");
		}
		mesID  = messageSave.saveReceiveMessage(myMessage); //保存信息用的，注意了啊啊啊啊！！！！
		if(mesID == -1)return mapping.findForward("newUserMessage.fail");
		//以下是输入信息的收件人，和收件人的所属邮箱
		for(int i = 0;i < Users.length; i++)
		{
			ReceiverInfo receiver = new ReceiverInfo();
			//设置收件人信息里面相关联的信息的ID号
			Message message = new Message();
			message.setMsId(mesID);
			receiver.setMessage(message);
			//设置接收人的邮箱
			receiver.setRiBox(riBox);
			//设置未读
			receiver.setRiRead("0");
			//设置未删除
			receiver.setRiDelete("0");
			//设置用户的ID
			SysUser sysUser = new SysUser();
			Long id;
			try
			{
				id = Long.parseLong(Users[i]);
			}
			catch(Exception ex)
			{
				ex.getStackTrace();
				return mapping.findForward("newUserMessage.fail");
			}
			sysUser.setSuId(id);
			receiver.setSysUser(sysUser);
			result = messageSave.saveReceiveUsers(receiver);
			if(result == -1)return mapping.findForward("newUserMessage.fail");
		}
		return mapping.findForward("newUserMessage.succeed");
	}
}