/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.ConfigWorkBean;
import com.icss.hit.bean.WorkPlanBean;
import com.icss.hit.bean.interfaces.ConfigWork;
import com.icss.hit.bean.interfaces.WorkPlanDao;
import com.icss.hit.hibernate.vo.Schedule;
import com.icss.hit.hibernate.vo.ScheduleConfig;
import com.icss.hit.hibernate.vo.SysUser;
import com.icss.hit.struts.form.AddWorkConfigForm;
import com.icss.hit.struts.form.ModifyCardForm;
import java.sql.Date;
/** 
 * 新建日程安排
 * Creation date: 08-03-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class NewWorkConfigAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		long userId =1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		WorkPlanDao cw = new WorkPlanBean();
		//得到该userId的所有的日程安排，以用来判断新建的安排时间是否冲突
		List<ScheduleConfig> sc = cw.getScheuleConfig(userId);
		request.setAttribute("sclist", sc);
		return mapping.findForward("NewWorkConfig.succeed");
	}
}