/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.bean.OtherInfoBean;
import com.icss.hit.bean.interfaces.OtherInfo;
import com.icss.hit.component.CreatPdf;
import com.icss.hit.hibernate.vo.SysUser;
import com.icss.hit.struts.form.SearchOtherInfoForm;


/** 
 * 导出搜索他人的资料为PDF文件
 * Creation date: 08-05-2009
 * @author 万里鹏
 * XDoclet definition:
 * @struts.action path="/OtherInfoPDF" name="searchOtherInfoForm" input="/OtherInfo.do" scope="request" validate="true"
 * @struts.action-forward name="OtherInfoPDF.succeed" path="/login.jsp"
 */
public class OtherInfoPDFAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchOtherInfoForm searchInfoForm = (SearchOtherInfoForm) form;// TODO Auto-generated method stub
		long uid = 1L; // 用户ID
		if( request.getSession().getAttribute("UserId") != null ){
			uid = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 搜索的类型，员工号或者姓名
		String type = searchInfoForm.getType();
		// 关键词
		String key = searchInfoForm.getSuUser();
		// 性别
		String sex= searchInfoForm.getSuSex();
		// 部门ID
		int dept = Integer.parseInt(searchInfoForm.getSuDept());
		
		OtherInfo info = new OtherInfoBean();
		// 得到符合条件的人的信息
		List<SysUser> list = info.getAllSearchedUserInfo(type, key, sex, dept);
		Date date = new Date();
		String title="OA协同办公系统";
		String para1Str="导出日期：" + date.toLocaleString();
		String para2Str="由Surmounters小组制作";
		
		try{
			//1。生成要产生pdf文件的对象--------------开始	
			CreatPdf createPdf=new CreatPdf();
			
			createPdf.setFont("STSong-Light",32,"blue","Font.BOLD");
			String pdfName = date.getTime() + "_" + uid + ".pdf";
			createPdf.setFileName(request.getRealPath("/pdf/")  + "\\" + pdfName );

			//1.生成要产生pdf文件的对象--------------结束
			//2.给文章添加内容-----------------开始
			//A。添加段内容-----------开始			
			createPdf.addAlignContent(title,"center");
			createPdf.setFont("宋体",8,"black","Font.NORMAL");
			createPdf.addContentLn(para1Str);
			createPdf.addContentLn(para2Str);
			
			for( int i = 0; i < list.size(); i++ ){
				SysUser user = list.get(i);
				
				createPdf.addAlignContent( user.getSuUsername() + "的个人资料","center");
				// 对表格进行设置				
				createPdf.setTable(6,7);
				createPdf.setCellAlign("center");
				createPdf.setTableBW(3);
				createPdf.setTableBC("black");
				createPdf.setTablePadd(1);
				createPdf.setTableSpac(0);
				
				// 员工号
				createPdf.setCell("员工号");
				createPdf.setCellColspan(2);
				createPdf.addTableCell();
				
				createPdf.setCell(user.getSuUid());
				createPdf.setCellColspan(4);
				createPdf.addTableCell();
				
				// 一行完毕
				createPdf.setTableEndHead();
				createPdf.setCell("姓名");
				createPdf.addTableCell();
				createPdf.setCell(user.getSuUsername());
				createPdf.addTableCell();
				createPdf.setCell("性别");
				createPdf.addTableCell();
				createPdf.setCell(user.getSuSex());
				createPdf.addTableCell();
				createPdf.setCell("所属部门");
				createPdf.addTableCell();
				createPdf.setCell(user.getSysDept().getSdName());
				createPdf.addTableCell();
				createPdf.setTableEndHead();
							
				createPdf.setCell("职位");
				createPdf.addTableCell();
				createPdf.setCell(user.getSysPosition().getSpsName());
				createPdf.addTableCell();
				createPdf.setCell("办公电话");
				createPdf.addTableCell();
				createPdf.setCell(user.getSuTel());
				createPdf.addTableCell();
				createPdf.setCell("移动电话");
				createPdf.addTableCell();
				createPdf.setCell(user.getSuCellphone());
				createPdf.addTableCell();
				createPdf.setTableEndHead();
				
				createPdf.setCell("系统角色");
				createPdf.addTableCell();
				createPdf.setCell(user.getSysRole().getSrName());
				createPdf.addTableCell();
				createPdf.setCell("电子邮件");
				createPdf.addTableCell();
				createPdf.setCell(user.getSuEmail());
				createPdf.setCellColspan(2);
				createPdf.addTableCell();


				createPdf.setCell("");
				createPdf.addTableCell();
				createPdf.setTableEndHead();
				
				createPdf.setCell("个人爱好");
				createPdf.addTableCell();
				createPdf.setCell(user.getSuHobby());
				createPdf.setCellColspan(5);
				createPdf.addTableCell();
				createPdf.setTableEndHead();
	
				createPdf.setCell("个人简介：" + user.getSuInfos());
				createPdf.setCellColspan(6);
				createPdf.addTableCell();
				
				createPdf.addTable();
				createPdf.addAlignContent( "\n\n\n\n","center");
			}
			//3.保存文件
			createPdf.save();
			System.out.println("生成PDF完成");
			
			
			String keyUrl = null;
			String sexUrl = null;
			try {
				keyUrl = URLEncoder.encode(key, "UTF-8");
				sexUrl = URLEncoder.encode(sex, "UTF-8");
				System.out.println(keyUrl);
			} catch (UnsupportedEncodingException e) {
				return mapping.findForward("OtherInfoPDF.succeed");
			}
			// 带参数的页面跳转
			ActionRedirect redirect = new ActionRedirect(mapping.findForward("OtherInfoPDF.succeed"));
			redirect.addParameter("type",type);
			redirect.addParameter("key", keyUrl);
			redirect.addParameter("sex", sexUrl);
			redirect.addParameter("dept", dept);
			redirect.addParameter("page", 1);
			redirect.addParameter("pdf", pdfName);
			return redirect;
		}catch(Exception e){
			e.printStackTrace();
			//System.out.println(e);
		}
		return mapping.findForward("OtherInfoPDF.error");
	}
}