/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.icss.hit.bean.*;
import com.icss.hit.hibernate.vo.*;

/** 
 * MyEclipse Struts
 * Creation date: 07-30-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="oterUserDetail.success" path="/info/otherUserDetail.jsp"
 */
public class OtherUserDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		long otherUserId = -1;//存储查询字符串中的用户ID参数

		UserInfoBean getter = null;//用户信息获取Bean
		SysUser otherUser = null;//用户信息实体
		String id = request.getParameter("userId");//先用String存 再转换成Long
		try{
			if( id != null)
				otherUserId = Long.parseLong(id);
			
			else
				return mapping.findForward("otherUserDetail.error");
		}
		catch (Exception e){
			e.printStackTrace();
			return mapping.findForward("otherUserDetail.error");
		}
		
		getter = new UserInfoBean();
		otherUser = getter.getUserInfo(otherUserId);//从数据库中取数据
		
		try{
			if(otherUser != null){
				otherUser.setPath(request.getRealPath("/headphoto/")+"\\");
				request.setAttribute("otherUserInfo",otherUser);
				return mapping.findForward("otherUserDetail.success");//正确的映射
			}
			else
				return mapping.findForward("otherUserDetail.error");
		}
		catch (Exception e){
			return mapping.findForward("otherUserDetail.error");
		}
		
		
	}
}