/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;


import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import com.icss.hit.bean.MessageSaveBean;
import com.icss.hit.bean.WorkPlanBean;
import com.icss.hit.bean.interfaces.MessageDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.Message;
import com.icss.hit.hibernate.vo.MessageReceivers;
import com.icss.hit.hibernate.vo.ReceiverInfo;


/** 
 * MyEclipse Struts
 * Creation date: 08-07-2009
 * 
 * XDoclet definition:
 * @struts.action path="/inbox" name="inboxForm" input="/message/inbox.jsp" scope="request" validate="true"
 */
public class OutboxAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		long userId = 1L;
		// 得到用户ID
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		MessageDao md = new MessageSaveBean();
		// 得到发件箱的数量
		int count = md.getOutBoxCount(userId);
		System.out.println("返回的数量"+count);
		int pageCount =0;
		if( count != 0 ){
			// 得到总页数
			pageCount = md.getPageCount(count, MessageSaveBean.PAGE_SIZE);
		}
		
		// 当前页数
		int pageNo = 1;
		if( request.getParameter("page") != null ){
			try{
				pageNo = Integer.parseInt(request.getParameter("page"));
			}catch( Exception e){
				pageNo = 1;
			}
		}
		// 得到当前页数的内容
		if( pageCount != 0){
			List<MessageReceivers> list = md.getOutboxByPage(userId, pageNo);
			//System.out.println("发件箱大小"+list.size());
			request.setAttribute("riList", list);
			// 输出分页的信息
			PageBean bean = new PageBean();
			bean.setTotal(pageCount);
			bean.setLink("./outbox.do");
			bean.setThispage(pageNo);
			request.setAttribute("page", bean.getPageString());
		}
		return mapping.findForward("Outbox.succeed");
	}
}