/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CheckPower;

/** 
 * 输出图片的
 * Creation date: 08-10-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="outputGraph.successd" path="/adminmeeting/outputGraph.jsp"
 */
public class OutputGraphAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前用户ID
		long userId = -1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 判断用户权限
		CheckPower check = new CheckPower(userId);
		check.getPower();
		if( !check.check(CheckPower.ADMIN_ROOM_REG)){
			return mapping.findForward("NullLogin");
		}
		
		if(request.getParameter("pic") != null&&request.getParameter("month") != null)
		{
			request.setAttribute("pic", request.getParameter("pic"));
			request.setAttribute("month", request.getParameter("month"));
			request.setAttribute("year", request.getParameter("year"));
		}
		//没有数据的时候发生的错误
		if(request.getAttribute("conflict") != null)
		{
			//这个地方加上pic原因是发生错误的时候，可以保持前面的数据，从roomExcelExportAction来的
			request.setAttribute("conflict", request.getAttribute("conflict"));
			request.setAttribute("pic", request.getAttribute("pic"));
			request.setAttribute("month", request.getAttribute("month"));
			request.setAttribute("year", request.getAttribute("year"));
		}
		
		//查询发生错误的时候
		if(request.getAttribute("roomRegsErrors") != null)
		{
			//这个地方加上pic原因是发生错误的时候，可以保持前面的数据，从roomExcelExportAction来的
			request.setAttribute("roomRegsErrors", request.getAttribute("roomRegsErrors"));
			request.setAttribute("pic", request.getAttribute("pic"));
			request.setAttribute("month", request.getAttribute("month"));
			request.setAttribute("year", request.getAttribute("year"));
		}
		
		//传递Excel文件名
		if(request.getParameter("excel") != null)request.setAttribute("ExcelName", request.getParameter("excel"));
		return mapping.findForward("outputGraph.successd");
	}
}