/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * 本方法只为点击修改密码之后的页面跳转，并没有实现逻辑功能
 * Creation date: 08-03-2009
 * @author 万里鹏
 * @struts.action validate="true"
 * @struts.action-forward name="Password.succeed" path="/info/modifyPassword.jsp"
 * @struts.action-forward name="Password.error" path="/login.jsp"
 */
public class PasswordAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("Password.succeed");
	}
}