/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.ConfigWorkBean;
import com.icss.hit.bean.WorkListBean;
import com.icss.hit.bean.interfaces.ConfigWork;
import com.icss.hit.bean.interfaces.WorkList;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.Schedule;

/** 
 * 得到待办事项清单
 * Creation date: 08-05-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="planListMore.succeed" path="/work/planListMore.jsp"
 */
public class PlanListMoreAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前登录用户ID
		long id=-1;
		if( request.getSession().getAttribute("UserId") != null ){
			id = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 查询页码
		int pageNo = 1;
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			pageNo =1;
		}
		
		// 所有人员的数量
		int count = 0;
		// 分页的数量
		int pageCount = 0;
		// 得到搜索的数据
		List<Schedule> list = null;
		if( id != -1){
			WorkList work = new WorkListBean();
			
			// 得到总数和分页
			count = work.getAllWorkPlanCount(id);
			pageCount = work.getPageCount(count, WorkListBean.PAGE_SIZE);
			
			// 设置页面的范围
			pageNo = pageNo < 1? 1:pageNo;
			pageNo = pageNo > pageCount? pageCount: pageNo;
			
			list = work.getAllWorkPlan(id, pageNo);
			request.setAttribute("allWorkPlanList", list);
						
			// 生成前面的页面显示
			PageBean pagebean = new PageBean();
			pagebean.setLink("planListMore.do");
			pagebean.setTotal(pageCount);
			pagebean.setThispage(pageNo);
			
			request.setAttribute("pageString", pagebean.getPageString());
		}
		return mapping.findForward("planListMore.succeed");
	}
}