/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.MessageSaveBean;
import com.icss.hit.bean.interfaces.MessageDao;
import com.icss.hit.hibernate.vo.MessageReceivers;

/** 
 * MyEclipse Struts
 * Creation date: 08-11-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ReadOutMessageAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String msID = request.getParameter("msID");
		//为空的时候或者不为数字的时候
		if(msID == null&&!(msID.matches("[1-9]\\d*")))return mapping.findForward("readOutMessage.fail");
		long ID = Long.parseLong(msID);
		//不为空的时候或者为数字的时候
		MessageDao mesOperation = new MessageSaveBean();
		
		MessageReceivers messageInfo = new MessageReceivers();
		//由于草稿箱的操作相同，所以可以调用相同的方法。
		messageInfo = mesOperation.getDraftMessage(ID);
		String[] receivers = messageInfo.getReceiverInfos();
		String name="";
		for(int i=0;i<receivers.length;i++)
		{
			//构建字符串，最后一个没有逗号
			if(i!=receivers.length-1)name+=(receivers[i] + " , ");
			else name+=receivers[i];
		}
		request.setAttribute("receivers", name);
		request.setAttribute("messageInfo", messageInfo);
		return mapping.findForward("readOutMessage.successd");
	}
}