/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.RoomBean;
import com.icss.hit.bean.interfaces.RoomDao;
import com.icss.hit.hibernate.vo.RoomReg;

/** 
 * 会议室申请记录详细信息
 * Creation date: 08-08-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="registerMeetingRoomLogDetails.succeed" path="/meeting/registerMeetingRoomLogDetails.jsp"
 * @struts.action-forward name="registerMeetingRoomLogDetails.failed" path="/meeting/registerMeetingRoomLogDetails.jsp"
 */
public class RegisterMeetingRoomLogDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 用户ID
		long userId=-1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		// RoomReg表ID
		long rrId=-1;
		// 页码
		int pageNo=1;
		// 存放跳转参数
		String forwardString=null;
		try{
			rrId=Long.parseLong(request.getParameter("rrId"));
		}
		catch(Exception e){
			rrId=-1;
			pageNo=1;
		}
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			pageNo=1;
		}
		if(rrId!=-1){
			RoomReg room = new RoomReg();
			RoomDao roomDao = new RoomBean();
			// 得到详细信息
			room=roomDao.getRoomRegDetails(rrId, userId);
			request.setAttribute("roomRegDetails", room);
			forwardString="registerMeetingRoomLog.do?page="+pageNo;
			request.setAttribute("forwardString", forwardString);
			return mapping.findForward("registerMeetingRoomLogDetails.succeed");
		}
		return mapping.findForward("registerMeetingRoomLogDetails.failed");
	}
}