/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CheckPower;
import com.icss.hit.bean.ConfigWorkBean;
import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.SysPositionBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.bean.interfaces.SysPositionDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.SysDept;
import com.icss.hit.hibernate.vo.SysUser;

/** 
 * 根据部门列出所有员工信息
 * Creation date: 08-11-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="roleArrage.succeed" path="/role/roleArrage.jsp"
 */
public class RoleArrangeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		// 当前用户ID
		long userId = -1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 判断用户权限
		CheckPower check = new CheckPower(userId);
		check.getPower();
		if( !check.check(CheckPower.ADMIN_STUFF_INFO) && !check.check(CheckPower.ADMIN_ROLE)){
			return mapping.findForward("NullLogin");
		}
		
		Department deptm = new DepartmentBean();
		// 得到所有的部门信息
		List<SysDept> deptList = deptm.getAllDept();
		request.setAttribute("deptList",deptList);
		
		// 存放部门编号
		int dept = -1;
		// 存放页码
		int pageNo = 1;
		
		try{
			dept = Integer.parseInt(request.getParameter("dept"));
		}catch(Exception e){
			// 如果数据异常
			dept = 0;
		}
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}catch(Exception e){
			// 如果数据异常
			pageNo = 1;
		}
		// 所有人员的数量
		int count = 0;
		// 分页的数量
		int pageCount = 0;
		// 得到搜索的数据
		List<SysUser> list = null;
		if( dept != -1){
			SysPositionDao pos = new SysPositionBean();
			
			// 得到总数和分页
			count = pos.getAllUserByDeptCount(dept);
			pageCount = pos.getPageCount(count, SysPositionBean.PAGE_SIZE);

			// 设置页面的范围
			pageNo = pageNo < 1? 1:pageNo;
			pageNo = pageNo > pageCount? pageCount: pageNo;
			
			list = pos.getAllUserByDept(dept, pageNo);
			request.setAttribute("allOtherUserInfoList", list);
						
			// 生成前面的页面显示
			PageBean pagebean = new PageBean();
			pagebean.addParam("dept=" + dept );
			pagebean.setLink("roleArrange.do");
			pagebean.setTotal(pageCount);
			pagebean.setThispage(pageNo);
			
			
			request.setAttribute("pageString", pagebean.getPageString());
			request.setAttribute("searchDept",dept);
			request.setAttribute("pageNo",pageNo );
		}
		return mapping.findForward("roleArrange.succeed");
	}
}