/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.FindAllRoom;
import com.icss.hit.bean.interfaces.FindAllRoomDao;
import com.icss.hit.hibernate.vo.Room;

/** 
 * 用于发现房间并且转向显示页面
 * Creation date: 08-08-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="roomRedirect.fail" path="/login.jsp"
 * @struts.action-forward name="roomRedirect.successd" path="/meeting/roomRegist.jsp"
 */
public class RoomRedirectAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//找出可以使用的房间，传递过去
		FindAllRoomDao rooms = new FindAllRoom();
		List<Room> roomList = rooms.getAllRoom();
		request.setAttribute("roomList", roomList);
		return mapping.findForward("roomRedirect.successd");
	}
}