/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.struts.form.SearchShareCardUserForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-03-2009
 * 
 * XDoclet definition:
 * @struts.action path="/searchShareCardUser" name="searchShareCardUserForm" input="/form/searchShareCardUser.jsp" scope="request" validate="true"
 * @struts.action-forward name="searchShareCardUser.succeed" path="/shareCard.do"
 */
public class SearchShareCardUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchShareCardUserForm searchShareCardUserForm = (SearchShareCardUserForm) form;// TODO Auto-generated method stub
		String key = searchShareCardUserForm.getSuUser();
		String sex = searchShareCardUserForm.getSuSex();
		String keyUrl = null;
		String sexUrl = null;
		try {
			keyUrl = URLEncoder.encode(key, "UTF-8");
			sexUrl = URLEncoder.encode(sex, "UTF-8");
			System.out.println(keyUrl);
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return mapping.findForward("searchShareCardUser.succeed");
		}
		
		// 带参数的页面跳转
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("searchShareCardUser.succeed"));
		redirect.addParameter("type",searchShareCardUserForm.getType());
		redirect.addParameter("key", keyUrl);
		redirect.addParameter("sex", sexUrl);
		redirect.addParameter("dept", searchShareCardUserForm.getSuDept());
		redirect.addParameter("page", 1);
		return redirect;
	}
}