/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.struts.form.SearchOtherInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2009
 * 
 * XDoclet definition:
 * @struts.action path="/SearchOtherInfo" name="searchOtherInfoForm" input="/OtherInfo.do" scope="request" validate="true"
 * @struts.action-forward name="SearchOtherInfo.succeed" path="/OtherInfo.do"
 */
public class SearchOtherInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchOtherInfoForm searchOtherInfoForm = (SearchOtherInfoForm) form;
		String key = searchOtherInfoForm.getSuUser();
		String sex = searchOtherInfoForm.getSuSex();
		String keyUrl = null;
		String sexUrl = null;
		try {
			keyUrl = URLEncoder.encode(key, "UTF-8");
			sexUrl = URLEncoder.encode(sex, "UTF-8");
			//System.out.println(keyUrl);
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return mapping.findForward("SearchOtherInfo.succeed");
		}
		
		// 带参数的页面跳转
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("SearchOtherInfo.succeed"));
		redirect.addParameter("type",searchOtherInfoForm.getType());
		redirect.addParameter("key", keyUrl);
		redirect.addParameter("sex", sexUrl);
		redirect.addParameter("dept", searchOtherInfoForm.getSuDept());
		redirect.addParameter("page", 1);
		return redirect;
	}
}