/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.struts.form.SearchShareFileForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-09-2009
 * 
 * XDoclet definition:
 * @struts.action path="/SearchShareFile" name="searchShareFileForm" input="/filepage/searchShareFile.jsp" scope="request" validate="true"
 * @struts.action-forward name="SearchShareFile.succeed" path="/filepage/fileUpload.jsp"
 * @struts.action-forward name="SearchShareFile.error" path="/filepage/fileUpload.jsp"
 */
public class SearchShareFileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchShareFileForm searchShareFileForm = (SearchShareFileForm) form;// TODO Auto-generated method stub
		String type = searchShareFileForm.getType();
		String key = searchShareFileForm.getKey();
		String filename = searchShareFileForm.getFileName();
		
		String keyUrl = null;
		String filenameUrl = null;
		try {
			keyUrl = URLEncoder.encode(key, "UTF-8");
			filenameUrl = URLEncoder.encode(filename, "UTF-8");
			
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return mapping.findForward("SearchShareFile.error");
		}
		
		// 带参数的页面跳转
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("SearchShareFile.succeed"));
		redirect.addParameter("type",type);
		redirect.addParameter("key", keyUrl);
		redirect.addParameter("filename", filenameUrl);
		redirect.addParameter("page", 1);
		return redirect;
	}
}