/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.struts.form.SearchAvailableRoomForm;
import com.icss.hit.struts.form.SearchOtherInfoForm;

/** 
 * 得到搜索参数(搜索可用会议室)
 * Creation date: 08-08-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action path="/searchAvailableRoom" name="searchAvailableRoomForm" input="/form/searchAvailableRoom.jsp" scope="request" validate="true"
 */
public class SearchAvailableRoomAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchAvailableRoomForm searchAvailableRoomForm = (SearchAvailableRoomForm) form;// TODO Auto-generated method stub
		// 存放当前用户ID
		long userId=-1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 得到输入参数
		String name = searchAvailableRoomForm.getName();
		String containNum = searchAvailableRoomForm.getContainNum();
		String beginTime = searchAvailableRoomForm.getBeginTime();
		String endTime = searchAvailableRoomForm.getEndTime();
		String nameUrl = null;
		try {
			if(name!=null &&(!name.equals(""))){
				nameUrl = URLEncoder.encode(name, "UTF-8");
			}
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return mapping.findForward("searchAvailableRoom.failed");
		}
		// 带参数的页面跳转
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("searchAvailableRoom.succeed"));

		redirect.addParameter("name",nameUrl);
		redirect.addParameter("containNum", containNum);
		redirect.addParameter("beginTime", beginTime);
		redirect.addParameter("endTime", endTime);
		redirect.addParameter("page", 1);
		return redirect;
	}
}