/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import com.icss.hit.struts.form.SearchInBoxForm;

/** 
 * 得到搜索参数(搜索收件箱)
 * Creation date: 08-06-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action path="/searchInBox" name="searchInBoxForm" input="/form/searchInBox.jsp" scope="request" validate="true"
 * @struts.action-forward name="searchInBox.succeed" path="/message/inBox.jsp"
 * @struts.action-forward name="searchInBox.failed" path="/message/inBox.jsp"
 */
public class SearchInBoxAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchInBoxForm searchInBoxForm = (SearchInBoxForm) form;
		// 存放当前用户ID
		long userId=-1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		String searchType = searchInBoxForm.getSearchType();
		String content = searchInBoxForm.getContents();
		String contentUrl = null;
		try {
			if(content!=null){
				contentUrl = URLEncoder.encode(content, "utf-8");
			}
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
			return mapping.findForward("searchInBox.failed");
		}
		//带参数的页面跳转
		ActionRedirect redirect = new ActionRedirect(mapping.findForward("searchInBox.succeed"));
		redirect.addParameter("searchType",searchType);
		redirect.addParameter("content", contentUrl);
		redirect.addParameter("pageNo", 1);
	    return redirect;
	}
}