/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CardBean;
import com.icss.hit.bean.CardTypeBean;
import com.icss.hit.bean.interfaces.CardDao;
import com.icss.hit.bean.interfaces.CardTypeDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.Card;
import com.icss.hit.hibernate.vo.CardType;


/** 
 * 根据条件搜索个人名片夹信息
 * Creation date: 08-01-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SelfCardAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String userName = null;
		String company = null;
		long uId = 1 ;
		if( request.getSession().getAttribute("UserId") != null ){
			uId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		int userSex = -1;
		int cardType = -1;
		int pageNo = 1;
		
		CardTypeDao type = new CardTypeBean();
		List<CardType> cardTypeList = type.getAllCardType(uId);
		request.setAttribute("cardTypeList",cardTypeList);
		
		// 得到参数
		userName = request.getParameter("userName");
		company = request.getParameter("company");
		try {
			if( userName != null)
				userName = URLDecoder.decode(userName, "utf-8");
			if( company != null)
				company = URLDecoder.decode(company, "utf-8");
		} catch (UnsupportedEncodingException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
			userName = null;
			company = null;
		}
		
		try{
			cardType = Integer.parseInt(request.getParameter("cardType"));
			userSex = Integer.parseInt(request.getParameter("sex"));
			pageNo = Integer.parseInt(request.getParameter("page"));
		}catch(Exception e){
			// 如果数据异常
			cardType = -1;
			userSex = -1;
			pageNo = 1;
		}
		// 所有人员的数量
		int count = 0;
		// 分页的数量
		int pageCount = 0;
		// 得到搜索的数据
		List<Card> list = null;
		// 分页处理
		PageBean pagebean = new PageBean();
		if( userName != null && company != null && userSex != -1 && cardType != -1 ){
			CardDao cardInfo = new CardBean();
			list = cardInfo.getSearchedCardInfo(userName,userSex,company,cardType,pageNo,uId);
			request.setAttribute("searchCardInfo", list);
			// 得到总数和分页
			count = cardInfo.getSearchedCardCount(userName,userSex,company,cardType,uId);
			pageCount = cardInfo.getPageCount(count, CardBean.PAGE_SIZE);
			
			// 设置页面的范围
			pageNo = pageNo < 1? 1:pageNo;
			pageNo = pageNo > count? count: pageNo;
			
			// 生成前面的页面显示
			
			pagebean.addParam("userName=" + URLEncoder.encode(request.getParameter("userName")) );
			pagebean.addParam("company="+URLEncoder.encode(request.getParameter("company")));
			pagebean.addParam("sex=" + userSex );
			pagebean.addParam("cardType=" + cardType );
			
			pagebean.setLink("selfCard.do");
			pagebean.setTotal(pageCount);
			pagebean.setThispage(pageNo);
			//保存用户搜索参数
			request.setAttribute("pageString", pagebean.getPageString());
			
			request.setAttribute("search", "searchFlag");//ddd在这里添加了一行用于显示没有搜索到的时候显示什么
		}
		request.setAttribute("searchName",userName);
		request.setAttribute("searchSex",userSex);
		request.setAttribute("searchCompany",company);
		request.setAttribute("searchCardType",cardType);
		
		
		return mapping.findForward("selfCard.succeed");
	}
}