/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CheckPower;
import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.SysPositionBean;
import com.icss.hit.bean.UserInfoBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.bean.interfaces.SysPositionDao;
import com.icss.hit.bean.interfaces.UserInfo;
import com.icss.hit.hibernate.vo.SysDept;
import com.icss.hit.hibernate.vo.SysPosition;
import com.icss.hit.hibernate.vo.SysUser;

/** 
 * 得到需要更改信息的用户
 * Creation date: 08-12-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="setUpInfo" path="/role/setUpInfo.jsp"
 */
public class SetUpInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前登录用户ID
		long userId = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		// 判断用户权限
		CheckPower check = new CheckPower(userId);
		check.getPower();
		if( !check.check(CheckPower.ADMIN_STUFF_INFO)){
			return mapping.findForward("NullLogin");
		}
		
		
		long workerId = -1;//存储查询字符串中的用户ID参数
		long dept = 0; // 部门号
		int pageNo = 1; // 页码

		String id = request.getParameter("suId");//先用String存 再转换成Long
		try{
			if( id != null){
				workerId = Long.parseLong(id);
			}
		}
		catch (Exception e){
			e.printStackTrace();
			return mapping.findForward("setUpInfo.succeed");
		}
		try{
			dept = Integer.parseInt(request.getParameter("dept"));
			pageNo = Integer.parseInt(request.getParameter("page"));
		}catch(Exception e){
			// 如果数据异常
			dept = 0;
			pageNo = 1;
		}
		
		Department deptm = new DepartmentBean();
		// 得到所有的部门信息
		List<SysDept> deptList = deptm.getAllDept();
		request.setAttribute("deptList",deptList);
		
		SysPositionDao pos = new SysPositionBean();
		// 得到所有职位列表
		List<SysPosition> posList = pos.getAllPosition();
		request.setAttribute("posList",posList);
		
		UserInfo info = new UserInfoBean();
		SysUser user = info.getUserInfo(workerId);
		request.setAttribute("userInfo",user);
		user.setPath(request.getRealPath("/headphoto/")+"\\");
		request.setAttribute("dept",dept);
		request.setAttribute("page", pageNo);
		return mapping.findForward("setUpInfo.succeed");
	}
}