/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.FileBean;
import com.icss.hit.bean.interfaces.FileDao;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.Files;

/** 
 * MyEclipse Struts
 * Creation date: 08-09-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="ShareFile.succeed" path="/filepage/searchShareFile.jsp"
 */
public class ShareFileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String type = request.getParameter("type");
		String key = request.getParameter("key");
		String filename = request.getParameter("filename");
		String page = request.getParameter("page");
		
		try {
			if( key != null){
				key = URLDecoder.decode(key,"UTF-8");
			}
			if( filename != null)
				filename = URLDecoder.decode(filename, "UTF-8");
		} catch (UnsupportedEncodingException e1) {
			e1.printStackTrace();
			key = null;
		}
		
		int pageNo = 1;
		try{
			pageNo = Integer.parseInt(page);
		}catch(Exception e){
			pageNo = 1;
		}
		
		FileDao fileBean = new FileBean();
		
		int count = fileBean.searchShareFileCount(type, key, filename);
		int pageCount = fileBean.getPageCount(count, FileBean.PAGE_SIZE);
		
		pageNo = pageNo < 1? 1: pageNo;
		pageNo = pageNo > pageCount? pageCount: pageNo;
		
		List<Files> list = fileBean.searchShareFile(type, key, filename, pageNo);
		request.setAttribute("fileList", list);
		
		if( list != null ){
			// 生成前面的页面显示
			PageBean pagebean = new PageBean();
			pagebean.addParam("type=" + type );
			if(request.getParameter("key") != null)
				pagebean.addParam("key=" + URLEncoder.encode(request.getParameter("key")));
			else
				pagebean.addParam("key=");
			if( request.getParameter("filename") != null )
				pagebean.addParam("filename=" + URLEncoder.encode(request.getParameter("filename")));
			else
				pagebean.addParam("filename=");
			
			pagebean.setLink("ShareFile.do");
			pagebean.setTotal(pageCount);
			pagebean.setThispage(pageNo);
			
			request.setAttribute("pageString", pagebean.getPageString());

		}
		request.setAttribute("type", type);
		request.setAttribute("key", key);
		request.setAttribute("filename", filename);
		return mapping.findForward("ShareFile.succeed");
	}
}