/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.SysRoleBean;
import com.icss.hit.bean.interfaces.SysRoleDao;
import com.icss.hit.hibernate.vo.RolePower;

/** 
 * 用与读取数据库中角色和权限，转向显示出来
 * Creation date: 08-12-2009
 * @author 赵颖申
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="ShowRoles.successd" path="/role/roleList.jsp"
 * @struts.action-forward name="ShowRoles.fail" path="/role/roleList.jsp"
 */
public class ShowRolesAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<Long> IDList = new ArrayList<Long>();
		SysRoleDao sysRole = new SysRoleBean();
		List<RolePower> rolePowers = new ArrayList<RolePower>(); 
		//读取sysRole的所有ID
		IDList = sysRole.getRoleID();
		//返回角色和权限关系的集合
		rolePowers = sysRole.getRoleList(IDList);
		//设置到request里面去
		request.setAttribute("RolePowers", rolePowers);
		return mapping.findForward("ShowRoles.successd");
	}
}