/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.CardBean;
import com.icss.hit.bean.CardTypeBean;
import com.icss.hit.bean.interfaces.CardDao;
import com.icss.hit.hibernate.vo.Card;
import com.icss.hit.hibernate.vo.CardType;
import com.icss.hit.hibernate.vo.SysUser;
import com.icss.hit.struts.form.ModifyCardForm;
/** 
 * 修改名片
 * Creation date: 08-03-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ToModifyCardAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		long userId=1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		long cdid=1;
		//通过url取得名片的id的值
		String cdId = request.getParameter("cdId");
		try{
			if( cdId != null&&cdId.length()>0 ){
				 cdid = Long.parseLong(cdId);
			}
			else{
				cdid = ((ModifyCardForm)request.getAttribute("form")).getCd_id();
			}
		}catch( Exception e){
			return mapping.findForward("ToModifyCard.faild");
		}
		CardDao cd = new CardBean();
		Card card = cd.getCard(cdid);
		SysUser su =card.getCardType().getSysUser();
		//得到该userId的所有的名片夹分类
		List<CardType> list = new CardTypeBean().getAllCardType(userId);
		
		request.setAttribute("ctnameList", list);
		request.setAttribute("ct", card);
		
		try {
			//判断用户登录的id与通过名片的id获得的用户的id是否相等
			if (su.getSuId() == userId) {
				return mapping.findForward("ToModifyCard.succeed");
			} else {
				return mapping.findForward("ToModifyCard.faild");
			}
		} catch (Exception e) {
			return mapping.findForward("ToModifyCard.faild");
		}
	}
}