/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.UserInfoBean;
import com.icss.hit.bean.interfaces.UserInfo;
import com.icss.hit.hibernate.vo.SysUser;
import com.icss.hit.struts.form.UserInfoUpdatedForm;
/** 
 * MyEclipse Struts
 * Creation date: 07-30-2009
 * 
 * XDoclet definition:
 * @struts.action path="/userInfoUpdated" name="userInfoUpdatedForm" input="/info/userInfoUpdated.jsp" scope="request" validate="true"
 */
/**
 * @author xw-pc
 *
 */
public class UserInfoUpdatedAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserInfoUpdatedForm userInfoUpdatedForm = (UserInfoUpdatedForm) form;
		// 更新个人信息
		long userId = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		UserInfo info = new UserInfoBean();
		SysUser user = info.getUserInfo(userId);
		user.setSuId(userInfoUpdatedForm.getSu_id());
		user.setSuTel(userInfoUpdatedForm.getSu_tel());
		user.setSuCellphone(userInfoUpdatedForm.getSu_cellphone());
		user.setSuEmail(userInfoUpdatedForm.getSu_email());
		user.setSuHobby(userInfoUpdatedForm.getSu_hobby());
		user.setSuInfos(userInfoUpdatedForm.getSu_info());
		if(info.updateUserInfo(user))
		{
			return mapping.findForward("userInfoUpdated.successd");
		}
		else
		{
			return mapping.findForward("userInfoUpdated.faild");
		}
		
	}
}