/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.UserInfoBean;
import com.icss.hit.bean.interfaces.UserInfo;
import com.icss.hit.hibernate.vo.SysUser;

/** 
 * 修改个人信息
 * Creation date: 07-30-2009
 * @author xw-pc
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserInfoUpdateActionAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 取得用户信息
		long userId = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		UserInfo info = new UserInfoBean();
		
		SysUser user = info.getUserInfo(userId);
		request.setAttribute("userInfo",user);
		user.setPath(request.getRealPath("/headphoto/")+"\\");
		return mapping.findForward("userInfoUpdateAction.successd");
	}
}