/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.WorkPlanBean;
import com.icss.hit.hibernate.vo.Schedule;

/** 
 * 封装了现实某一日程安排的详细内容
 * Creation date: 08-03-2009
 * @author 万里鹏
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="WorkPlanDetail.succeed" path="/work/planDetail.jsp"
 * @struts.action-forward name="WorkPlanDetail.error" path="/work/workPlan.jsp"
 */
public class WorkPlanDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		long id;
		// 用户ID
		long userId = 1L;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		if(request.getParameter("id") == null){
			return mapping.findForward("WorkPlanDetail.error");
		}
		
		// 得到日程安排的ID
		try{
			id = Long.parseLong(request.getParameter("id").toString());
		}catch(Exception e){
			return mapping.findForward("WorkPlanDetail.error");
		}
		WorkPlanBean bean = new WorkPlanBean();
		Schedule sch = bean.getWorkPlan(id, userId);
		request.setAttribute("sch", sch);
		return mapping.findForward("WorkPlanDetail.succeed");
	}
}