/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.action;

import java.net.URLEncoder;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.icss.hit.bean.OtherInfoBean;
import com.icss.hit.bean.WorkListBean;
import com.icss.hit.bean.interfaces.WorkList;
import com.icss.hit.component.PageBean;
import com.icss.hit.hibernate.vo.Schedule;

/** 
 * 得到工作清单
 * Creation date: 08-05-2009
 * @author 朱金彪
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="workList.succeed" path="/work/workList.jsp"
 */
public class WorkListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 当前登录用户ID
		long userId = 1;
		if( request.getSession().getAttribute("UserId") != null ){
			userId = Long.parseLong(request.getSession().getAttribute("UserId").toString());
		}else{
			return mapping.findForward("NullLogin");
		}
		
		// 总记录条数
		int count=0;
		// 总页数
		int pageCount = 0;
		// 查询页码
		int pageNo = 1;
		try{
			pageNo = Integer.parseInt(request.getParameter("page"));
		}
		catch(Exception e){
			pageNo = 1;
		}
		List<Schedule> list = null;
		WorkList workList = new WorkListBean();
		// 得到总数和分页
		count = workList.getWorkListCount(userId);
		pageCount = workList.getPageCount(count, WorkListBean.PAGE_SIZE);
		
		// 设置页面的范围
		pageNo = pageNo < 1? 1:pageNo;
		pageNo = pageNo > pageCount? pageCount: pageNo;
		
		list = workList.getWorkList(userId, pageNo);
		request.setAttribute("workList", list);
					
		// 生成前面的页面显示
		PageBean pagebean = new PageBean();
		pagebean.setLink("workList.do");
		pagebean.setTotal(pageCount);
		pagebean.setThispage(pageNo);
		
		request.setAttribute("pageString", pagebean.getPageString());
		return mapping.findForward("workList.succeed");
	}
}