/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 08-08-2009
 * 
 * XDoclet definition:
 * @struts.form name="addMeetingRoomForm"
 */
public class AddMeetingRoomForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** room_name property */
	private String room_name;

	/** room_describe property */
	private String room_describe;

	/** room_capacity property */
	private String room_capacity;

	/*
	 * Generated Methods
	 */
	private ActionErrors validateRoomName(){
		ActionErrors errors = new ActionErrors();
		if(room_name == null || room_name.equals("")){
			errors.add("roomNameNull", new ActionMessage("AddMeetingRoom.roomNameNull"));
		}
		else if( room_name.length() > 30 ){
			errors.add("roomNameTooLong", new ActionMessage("AddMeetingRoom.roomNameTooLong"));
		}
		
		return errors;
	
	}
	private ActionErrors validateRoomDescribe(){
		ActionErrors errors = new ActionErrors();
		if( room_describe.length() > 2000 ){
			errors.add("roomDescribeTooLong", new ActionMessage("AddMeetingRoom.roomDescribeTooLong"));
		}
		
		return errors;
		
	}
	private ActionErrors validateRoomCapacity(){
		ActionErrors errors = new ActionErrors();
		if(room_capacity == null || room_capacity.equals("")){
			errors.add("roomCapacityNull", new ActionMessage("AddMeetingRoom.roomCapacityNull"));
		}
		else if( !room_capacity.matches("^[0-9]*[1-9][0-9]*$")){//判断是否是数字 使用正则表达式
			errors.add("roomCapacityNotNumic", new ActionMessage("AddMeetingRoom.roomCapacityNotNumic"));
		}

		return errors;
		
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();
		errors.add(validateRoomCapacity());
		errors.add(validateRoomName());
		errors.add(validateRoomDescribe());
		
		request.setAttribute("form", this);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the room_name.
	 * @return String
	 */
	public String getRoom_name() {
		return room_name;
	}

	/** 
	 * Set the room_name.
	 * @param room_name The room_name to set
	 */
	public void setRoom_name(String room_name) {
		this.room_name = room_name;
	}

	/** 
	 * Returns the room_describe.
	 * @return String
	 */
	public String getRoom_describe() {
		return room_describe;
	}

	/** 
	 * Set the room_describe.
	 * @param room_describe The room_describe to set
	 */
	public void setRoom_describe(String room_describe) {
		this.room_describe = room_describe;
	}

	/** 
	 * Returns the room_capacity.
	 * @return String
	 */
	public String getRoom_capacity() {
		return room_capacity;
	}

	/** 
	 * Set the room_capacity.
	 * @param room_capacity The room_capacity to set
	 */
	public void setRoom_capacity(String room_capacity) {
		this.room_capacity = room_capacity;
	}
}