/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 08-10-2009
 * 
 * XDoclet definition:
 * @struts.form name="addSysRoleForm"
 */
public class AddSysRoleForm extends ActionForm {
	/*
	 * Generated Methods
	 */
private String sr_name;
private String sp_name;
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();
		//权限表为空
		if(sr_name==null||sr_name.length()==0)
		{
			errors.add("sr_name", new ActionMessage("SrAdd.SrNameIsNull"));
		}
		request.setAttribute("form", this);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getSr_name() {
		return sr_name;
	}

	public void setSr_name(String sr_name) {
		this.sr_name = sr_name;
	}

	public String getSp_name() {
		return sp_name;
	}

	public void setSp_name(String sp_name) {
		this.sp_name = sp_name;
	}
}