/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2009
 * 
 * XDoclet definition:
 * @struts.form name="changeInfoForm"
 */
public class ChangeInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** suPos property */
	private String suPos;

	/** suSex property */
	private String suSex;

	/** suUid property */
	private String suUid;

	/** suUsername property */
	private String suUsername;

	/** suDept property */
	private String suDept;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the suPos.
	 * @return String
	 */
	public String getSuPos() {
		return suPos;
	}

	/** 
	 * Set the suPos.
	 * @param suPos The suPos to set
	 */
	public void setSuPos(String suPos) {
		this.suPos = suPos;
	}

	/** 
	 * Returns the suSex.
	 * @return Integer
	 */
	public String getSuSex() {
		return suSex;
	}

	/** 
	 * Set the suSex.
	 * @param suSex The suSex to set
	 */
	public void setSuSex(String suSex) {
		this.suSex = suSex;
	}

	/** 
	 * Returns the suUid.
	 * @return String
	 */
	public String getSuUid() {
		return suUid;
	}

	/** 
	 * Set the suUid.
	 * @param suUid The suUid to set
	 */
	public void setSuUid(String suUid) {
		this.suUid = suUid;
	}

	/** 
	 * Returns the suUsername.
	 * @return String
	 */
	public String getSuUsername() {
		return suUsername;
	}

	/** 
	 * Set the suUsername.
	 * @param suUsername The suUsername to set
	 */
	public void setSuUsername(String suUsername) {
		this.suUsername = suUsername;
	}

	/** 
	 * Returns the suDept.
	 * @return String
	 */
	public String getSuDept() {
		return suDept;
	}

	/** 
	 * Set the suDept.
	 * @param suDept The suDept to set
	 */
	public void setSuDept(String suDept) {
		this.suDept = suDept;
	}
}