/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2009
 * 
 * XDoclet definition:
 * @struts.form name="confirmAddWorkerForm"
 */
public class ConfirmAddWorkerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** suCellphone property */
	private String suCellphone;

	/** suPassword property */
	private String suPassword;

	/** suInfo property */
	private String suInfo;

	/** suRole property */
	private String suRole;

	/** suTel property */
	private String suTel;

	/** suPos property */
	private String suPos;

	/** suHobby property */
	private String suHobby;

	/** suSex property */
	private String suSex;

	/** suUid property */
	private String suUid;

	/** suEmail property */
	private String suEmail;

	/** suUsername property */
	private String suUsername;

	/** suDept property */
	private String suDept;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		if(suUid == null || suUid.length() == 0){
			errors.add("su_uid", new ActionMessage("AddWorker.UidIsNull"));
		}
		if(suUsername ==null||suUsername.length() == 0 ){
			errors.add("su_username", new ActionMessage("AddWorker.UsernameIsNull"));
		}
		if(suPassword == null||suPassword.length() == 0){
			errors.add("su_password", new ActionMessage("AddWorker.PasswordIsNull"));
		}
		if(suEmail!=null&&suEmail.length() > 100)
		{
				errors.add("su_email", new ActionMessage("UserInfoUpdate.EmailTooLong"));
			
		}
		if(suTel!=null&&suTel.length()>20)
		{
				errors.add("su_tel", new ActionMessage("UserInfoUpdate.TelTooLong"));
				
		
		}
		if(suCellphone!=null&&suCellphone.length()>20)
		{
				errors.add("su_cellphone", new ActionMessage("UserInfoUpdate.CellPhoneTooLong"));
		
		}
		if(suEmail!=null&&suEmail.length()>0)
		{
			if(!suEmail.matches("\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*"))
			{
				errors.add("su_email", new ActionMessage("UserInfoUpdate.Emailillegal"));
			}
		}
		if(suTel!=null&&suTel.length()>0)
		{
			if(!suTel.matches("1\\d{10}|\\d{3}-\\d{8}|\\d{4}-\\d{7,8}"))
			{
				errors.add("su_tel", new ActionMessage("UserInfoUpdate.Telillegal"));
			}
		}
		if(suCellphone!=null&&suCellphone.length()>0)
		{
			if(!suCellphone.matches("1\\d{10}|\\d{3}-\\d{8}|\\d{4}-\\d{7}"))
			{
				errors.add("su_cellphone", new ActionMessage("UserInfoUpdate.Cellphoneillegal"));
			}
		}
		
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the suCellphone.
	 * @return String
	 */
	public String getSuCellphone() {
		return suCellphone;
	}

	/** 
	 * Set the suCellphone.
	 * @param suCellphone The suCellphone to set
	 */
	public void setSuCellphone(String suCellphone) {
		this.suCellphone = suCellphone;
	}

	/** 
	 * Returns the suPassword.
	 * @return String
	 */
	public String getSuPassword() {
		return suPassword;
	}

	/** 
	 * Set the suPassword.
	 * @param suPassword The suPassword to set
	 */
	public void setSuPassword(String suPassword) {
		this.suPassword = suPassword;
	}

	/** 
	 * Returns the suInfo.
	 * @return String
	 */
	public String getSuInfo() {
		return suInfo;
	}

	/** 
	 * Set the suInfo.
	 * @param suInfo The suInfo to set
	 */
	public void setSuInfo(String suInfo) {
		this.suInfo = suInfo;
	}

	/** 
	 * Returns the suRole.
	 * @return String
	 */
	public String getSuRole() {
		return suRole;
	}

	/** 
	 * Set the suRole.
	 * @param suRole The suRole to set
	 */
	public void setSuRole(String suRole) {
		this.suRole = suRole;
	}

	/** 
	 * Returns the suTel.
	 * @return String
	 */
	public String getSuTel() {
		return suTel;
	}

	/** 
	 * Set the suTel.
	 * @param suTel The suTel to set
	 */
	public void setSuTel(String suTel) {
		this.suTel = suTel;
	}

	/** 
	 * Returns the suPos.
	 * @return String
	 */
	public String getSuPos() {
		return suPos;
	}

	/** 
	 * Set the suPos.
	 * @param suPos The suPos to set
	 */
	public void setSuPos(String suPos) {
		this.suPos = suPos;
	}

	/** 
	 * Returns the suHobby.
	 * @return String
	 */
	public String getSuHobby() {
		return suHobby;
	}

	/** 
	 * Set the suHobby.
	 * @param suHobby The suHobby to set
	 */
	public void setSuHobby(String suHobby) {
		this.suHobby = suHobby;
	}

	/** 
	 * Returns the suSex.
	 * @return String
	 */
	public String getSuSex() {
		return suSex;
	}

	/** 
	 * Set the suSex.
	 * @param suSex The suSex to set
	 */
	public void setSuSex(String suSex) {
		this.suSex = suSex;
	}

	/** 
	 * Returns the suUid.
	 * @return String
	 */
	public String getSuUid() {
		return suUid;
	}

	/** 
	 * Set the suUid.
	 * @param suUid The suUid to set
	 */
	public void setSuUid(String suUid) {
		this.suUid = suUid;
	}

	/** 
	 * Returns the suEmail.
	 * @return String
	 */
	public String getSuEmail() {
		return suEmail;
	}

	/** 
	 * Set the suEmail.
	 * @param suEmail The suEmail to set
	 */
	public void setSuEmail(String suEmail) {
		this.suEmail = suEmail;
	}

	/** 
	 * Returns the suUsername.
	 * @return String
	 */
	public String getSuUsername() {
		return suUsername;
	}

	/** 
	 * Set the suUsername.
	 * @param suUsername The suUsername to set
	 */
	public void setSuUsername(String suUsername) {
		this.suUsername = suUsername;
	}

	/** 
	 * Returns the suDept.
	 * @return String
	 */
	public String getSuDept() {
		return suDept;
	}

	/** 
	 * Set the suDept.
	 * @param suDept The suDept to set
	 */
	public void setSuDept(String suDept) {
		this.suDept = suDept;
	}
}