/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.icss.hit.bean.DepartmentBean;
import com.icss.hit.bean.SysPowerTypeBean;
import com.icss.hit.bean.interfaces.Department;
import com.icss.hit.bean.interfaces.SysPowerTypeDao;

/** 
 * MyEclipse Struts
 * Creation date: 08-11-2009
 * 
 * XDoclet definition:
 * @struts.form name="deleteSysPowerForm"
 */
public class DeleteSysPowerForm extends ActionForm {
	/*
	 * Generated Methods
	 */
private String spId;
	public String getSpId() {
	return spId;
}

public void setSpId(String spId) {
	this.spId = spId;
}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();
		long spid = Long.parseLong(spId);
		SysPowerTypeDao spt = new SysPowerTypeBean();
		//判断删除的权限里是否存在角色
		boolean check =spt.checkSysPower(spid) ;
		
		if(check==false)
		
		errors.add("DeleteSysPowerExist", new ActionMessage("DeleteSysPower.Exist"));
		
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}