/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-07-2009
 * 
 * XDoclet definition:
 * @struts.form name="fileUploadForm"
 */
public class FileUploadForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** fileFolder property */
	private String fileFolder;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the fileFolder.
	 * @return String
	 */
	public String getFileFolder() {
		return fileFolder;
	}

	/** 
	 * Set the fileFolder.
	 * @param fileFolder The fileFolder to set
	 */
	public void setFileFolder(String fileFolder) {
		this.fileFolder = fileFolder;
	}
}