/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-08-2009
 * 
 * XDoclet definition:
 * @struts.form name="folderFunctionForm"
 */
public class FolderFunctionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** newname property */
	private String newname;

	/** folderId property */
	private String folderId;

	/** flag property */
	private String flag;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the newname.
	 * @return String
	 */
	public String getNewname() {
		return newname;
	}

	/** 
	 * Set the newname.
	 * @param newname The newname to set
	 */
	public void setNewname(String newname) {
		this.newname = newname;
	}

	/** 
	 * Returns the folderId.
	 * @return String
	 */
	public String getFolderId() {
		return folderId;
	}

	/** 
	 * Set the folderId.
	 * @param folderId The folderId to set
	 */
	public void setFolderId(String folderId) {
		this.folderId = folderId;
	}

	/** 
	 * Returns the flag.
	 * @return String
	 */
	public String getFlag() {
		return flag;
	}

	/** 
	 * Set the flag.
	 * @param flag The flag to set
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}
}