/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-10-2009
 * 
 * XDoclet definition:
 * @struts.form name="graphOutputForm"
 */
public class GraphOutputForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** month property */
	private String month;

	/** year property */
	private String year;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the month.
	 * @return String
	 */
	public String getMonth() {
		return month;
	}

	/** 
	 * Set the month.
	 * @param month The month to set
	 */
	public void setMonth(String month) {
		this.month = month;
	}

	/** 
	 * Returns the year.
	 * @return String
	 */
	public String getYear() {
		return year;
	}

	/** 
	 * Set the year.
	 * @param year The year to set
	 */
	public void setYear(String year) {
		this.year = year;
	}
}