/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 07-28-2009
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class LoginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** code property */
	private String code;

	/** password property */
	private String password;

	/** username property */
	private String username;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		// 检验员工号
		if( username == null || username.equals("") || username.length() > 20){
			
			errors.add("username", new ActionMessage("Login.NullUsername"));
		}
		
		// 检验密码
		if( password == null || password.equals("") || password.length() > 20){
			errors.add("password", new ActionMessage("Login.NullPassword"));
		}
		
		//String validatecode = request.getSession().getAttribute("ValidateCode").toString().toLowerCase();
		// 检验验证码
		if( code == null || code.equals("") ){
			errors.add("code", new ActionMessage("Login.NullCode"));
		}
		else if(code.length() > 4 ){
			errors.add("code", new ActionMessage("Login.ErrorCode"));
		}
		
		request.setAttribute("form", this);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.username = null;
		this.password = null;
		this.code = null;
	}

	/** 
	 * Returns the code.
	 * @return String
	 */
	public String getCode() {
		return code;
	}

	/** 
	 * Set the code.
	 * @param code The code to set
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}