/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.icss.hit.bean.ManageRoomBean;
import com.icss.hit.bean.interfaces.manageRoomDao;

/** 
 * MyEclipse Struts
 * Creation date: 08-10-2009
 * 
 * XDoclet definition:
 * @struts.form name="manageAllRoomsForm"
 */
public class ManageAllRoomsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** roomID property */
	private String roomID;
	
	/** type property */
	private String type;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();
		manageRoomDao manageRoom = new ManageRoomBean();
		long roomid = Long.parseLong(request.getParameter("roomID"));
		System.out.println(roomid);
		if(type.equals("del"))
		{
			long isExistRegist = manageRoom.isExist(roomid);
			System.out.println(isExistRegist);
			//查询错误或者会议申请对该会议室不为空
			if(isExistRegist==-1||isExistRegist>0)
			{
				errors.add("roomError", new ActionMessage("roomError.Error"));
				return errors;
			}
			else return null;
		}
		else return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the roomID.
	 * @return String
	 */
	public String getRoomID() {
		return roomID;
	}

	/** 
	 * Set the roomID.
	 * @param roomID The roomID to set
	 */
	public void setRoomID(String roomID) {
		this.roomID = roomID;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}