/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/**
 * MyEclipse Struts Creation date: 08-08-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="modifyDeptForm"
 */
public class ModifyDeptForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** sd_tel property */
	private String sd_tel;

	/** sd_name property */
	private String sd_name;

	/** sd_id property */
	private String sd_id;

	/** sd_info property */
	private String sd_info;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {

		ActionErrors errors = new ActionErrors();
		
		// 部门的名称为空
		if (sd_name == null || sd_name.length() == 0) {
			errors.add("sd_nameError", new ActionMessage("SdAdd.NameIsNull"));
		}
		
		// 部门的电话不符合格式
		if (sd_tel != null && !sd_tel.matches("1\\d{10}|\\d{3}-\\d{8}|\\d{4}-\\d{7,8}")) {
			errors.add("sd_telError", new ActionMessage("SdAdd.Telillegal"));
		}
		request.setAttribute("form", this);
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the sd_tel.
	 * 
	 * @return String
	 */
	public String getSd_tel() {
		return sd_tel;
	}

	/**
	 * Set the sd_tel.
	 * 
	 * @param sd_tel
	 *            The sd_tel to set
	 */
	public void setSd_tel(String sd_tel) {
		this.sd_tel = sd_tel;
	}

	/**
	 * Returns the sd_name.
	 * 
	 * @return String
	 */
	public String getSd_name() {
		return sd_name;
	}

	/**
	 * Set the sd_name.
	 * 
	 * @param sd_name
	 *            The sd_name to set
	 */
	public void setSd_name(String sd_name) {
		this.sd_name = sd_name;
	}

	/**
	 * Returns the sd_id.
	 * 
	 * @return String
	 */
	public String getSd_id() {
		return sd_id;
	}

	/**
	 * Set the sd_id.
	 * 
	 * @param sd_id
	 *            The sd_id to set
	 */
	public void setSd_id(String sd_id) {
		this.sd_id = sd_id;
	}

	/**
	 * Returns the sd_info.
	 * 
	 * @return String
	 */
	public String getSd_info() {
		return sd_info;
	}

	/**
	 * Set the sd_info.
	 * 
	 * @param sd_info
	 *            The sd_info to set
	 */
	public void setSd_info(String sd_info) {
		this.sd_info = sd_info;
	}
}