/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-06-2009
 * 
 * XDoclet definition:
 * @struts.form name="searchInBoxForm"
 */
public class SearchInBoxForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** searchType property */
	private String searchType;

	/** content property */
	private String contents;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the searchType.
	 * @return String
	 */
	public String getSearchType() {
		return searchType;
	}

	/** 
	 * Set the searchType.
	 * @param searchType The searchType to set
	 */
	public void setSearchType(String searchType) {
		this.searchType = searchType;
	}

	/** 
	 * Returns the content.
	 * @return String
	 */
	public String getContents() {
		return contents;
	}

	/** 
	 * Set the content.
	 * @param content The content to set
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}
}