/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 08-08-2009
 * 
 * XDoclet definition:
 * @struts.form name="searchAvailableRoomForm"
 */
public class SearchAvailableRoomForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** beginTime property */
	private String beginTime;

	/** name property */
	private String name;

	/** containNum property */
	private String containNum;

	/** endTime property */
	private String endTime;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		System.out.println("进入验证");
		ActionErrors errors = new ActionErrors();
		if(containNum!=null && containNum.length()>0 && (!containNum.matches("[1-9]\\d*"))){
			System.out.println("数字不合法");
			errors.add("NotANumber",new ActionMessage("Meeting.NotANumber"));
			request.setAttribute("containNum",null);
			request.setAttribute("name",null);
			request.setAttribute("beginTime",null);
			request.setAttribute("endTime",null);
			return errors;
		}
		if(((beginTime!=null && beginTime.length()>0) && (endTime==null||endTime.length()==0))){
			System.out.println("时间没有同时填写");
			errors.add("StartEnd",new ActionMessage("Meeting.StartEnd"));
			request.setAttribute("containNum",null);
			request.setAttribute("name",null);
			request.setAttribute("beginTime",null);
			request.setAttribute("endTime",null);
			return errors;
		}
		if(((beginTime==null || beginTime.length()==0) && (endTime!=null && endTime.length()>0))){
			System.out.println("时间没有同时填写");
			errors.add("StartEnd",new ActionMessage("Meeting.StartEnd"));
			request.setAttribute("containNum",null);
			request.setAttribute("name",null);
			request.setAttribute("beginTime",null);
			request.setAttribute("endTime",null);
			return errors;
		}
		if(beginTime!=null&&endTime!=null&&beginTime.length()>0&&endTime.length()>0){
			try
			{
				SimpleDateFormat   bartDateFormat   =new   SimpleDateFormat("yyyy-MM-dd kk:mm:ss");
				Date begintime = bartDateFormat.parse(beginTime);
				Date endtime = bartDateFormat.parse(endTime);
				//判断开始时间是否晚于结束时间
				long i = begintime.getTime()-endtime.getTime();
				if(i>0)
				{
					System.out.println("时间颠倒");
					errors.add("TimeWrong", new ActionMessage("Meeting.TimeWrong"));
				}
			}
			catch (ParseException e)
			{
				System.out.println("时间格式不正确");
				errors.add("TimeFormatWrong", new ActionMessage("Meeting.TimeFormatWrong"));
			}
		}
		request.setAttribute("containNum",null);
		request.setAttribute("name",null);
		request.setAttribute("beginTime",null);
		request.setAttribute("endTime",null);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the beginTime.
	 * @return String
	 */
	public String getBeginTime() {
		return beginTime;
	}

	/** 
	 * Set the beginTime.
	 * @param beginTime The beginTime to set
	 */
	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the containNum.
	 * @return String
	 */
	public String getContainNum() {
		return containNum;
	}

	/** 
	 * Set the containNum.
	 * @param containNum The containNum to set
	 */
	public void setContainNum(String containNum) {
		this.containNum = containNum;
	}

	/** 
	 * Returns the endTime.
	 * @return String
	 */
	public String getEndTime() {
		return endTime;
	}

	/** 
	 * Set the endTime.
	 * @param endTime The endTime to set
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}
}