/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.icss.hit.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 08-01-2009
 * 
 * XDoclet definition:
 * @struts.form name="searchCardForm"
 */
public class SearchCardForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userName property */
	private String userName;

	/** cardType property */
	private String cardType;

	/** userSex property */
	private String userSex;

	/** company property */
	private String company;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		/*ActionErrors errors = new ActionErrors();
		if( userName == null || userName.equals("")||company ==null || company.equals("")){
			errors.add("nameCompError", new ActionMessage("SearchCard.nameCompError"));
		}
		return errors;*/
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the cardType.
	 * @return Integer
	 */
	public String getCardType() {
		return cardType;
	}

	/** 
	 * Set the cardType.
	 * @param cardType The cardType to set
	 */
	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	/** 
	 * Returns the userSex.
	 * @return String
	 */
	public String getUserSex() {
		return userSex;
	}

	/** 
	 * Set the userSex.
	 * @param userSex The userSex to set
	 */
	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	/** 
	 * Returns the company.
	 * @return String
	 */
	public String getCompany() {
		return company;
	}

	/** 
	 * Set the company.
	 * @param company The company to set
	 */
	public void setCompany(String company) {
		this.company = company;
	}
}